/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountId', 'model/AutomaticTransition', 'model/AutomaticTransitionInfoLinks', 'model/BeezUPCommonMarketplaceBusinessCode', 'model/BeezUPCommonMarketplaceTechnicalCode', 'model/BeezUPOrderStatus', 'model/BusinessOperationType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccountId'), require('./AutomaticTransition'), require('./AutomaticTransitionInfoLinks'), require('./BeezUPCommonMarketplaceBusinessCode'), require('./BeezUPCommonMarketplaceTechnicalCode'), require('./BeezUPOrderStatus'), require('./BusinessOperationType'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.AutomaticTransitionInfo = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.AccountId, root.BeezUpApi.AutomaticTransition, root.BeezUpApi.AutomaticTransitionInfoLinks, root.BeezUpApi.BeezUPCommonMarketplaceBusinessCode, root.BeezUpApi.BeezUPCommonMarketplaceTechnicalCode, root.BeezUpApi.BeezUPOrderStatus, root.BeezUpApi.BusinessOperationType);
  }
}(this, function(ApiClient, AccountId, AutomaticTransition, AutomaticTransitionInfoLinks, BeezUPCommonMarketplaceBusinessCode, BeezUPCommonMarketplaceTechnicalCode, BeezUPOrderStatus, BusinessOperationType) {
  'use strict';




  /**
   * The AutomaticTransitionInfo model module.
   * @module model/AutomaticTransitionInfo
   * @version 2.0
   */

  /**
   * Constructs a new <code>AutomaticTransitionInfo</code>.
   * @alias module:model/AutomaticTransitionInfo
   * @class
   * @implements module:model/AutomaticTransition
   * @param marketplaceTechnicalCode {module:model/BeezUPCommonMarketplaceTechnicalCode} 
   * @param accountId {module:model/AccountId} 
   * @param orderStatusTransitionId {Number} 
   * @param enabled {Boolean} 
   * @param marketplaceBusinessCode {module:model/BeezUPCommonMarketplaceBusinessCode} 
   * @param beezUPOrderStatus {module:model/BeezUPOrderStatus} 
   * @param businessOperationType {module:model/BusinessOperationType} 
   */
  var exports = function(marketplaceTechnicalCode, accountId, orderStatusTransitionId, enabled, marketplaceBusinessCode, beezUPOrderStatus, businessOperationType) {
    var _this = this;

    AutomaticTransition.call(_this, marketplaceTechnicalCode, accountId, orderStatusTransitionId, enabled);
    _this['marketplaceBusinessCode'] = marketplaceBusinessCode;
    _this['beezUPOrderStatus'] = beezUPOrderStatus;
    _this['businessOperationType'] = businessOperationType;

  };

  /**
   * Constructs a <code>AutomaticTransitionInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AutomaticTransitionInfo} obj Optional instance to populate.
   * @return {module:model/AutomaticTransitionInfo} The populated <code>AutomaticTransitionInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      AutomaticTransition.constructFromObject(data, obj);
      if (data.hasOwnProperty('marketplaceBusinessCode')) {
        obj['marketplaceBusinessCode'] = BeezUPCommonMarketplaceBusinessCode.constructFromObject(data['marketplaceBusinessCode']);
      }
      if (data.hasOwnProperty('beezUPOrderStatus')) {
        obj['beezUPOrderStatus'] = BeezUPOrderStatus.constructFromObject(data['beezUPOrderStatus']);
      }
      if (data.hasOwnProperty('businessOperationType')) {
        obj['businessOperationType'] = BusinessOperationType.constructFromObject(data['businessOperationType']);
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = AutomaticTransitionInfoLinks.constructFromObject(data['links']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BeezUPCommonMarketplaceBusinessCode} marketplaceBusinessCode
   */
  exports.prototype['marketplaceBusinessCode'] = undefined;
  /**
   * @member {module:model/BeezUPOrderStatus} beezUPOrderStatus
   */
  exports.prototype['beezUPOrderStatus'] = undefined;
  /**
   * @member {module:model/BusinessOperationType} businessOperationType
   */
  exports.prototype['businessOperationType'] = undefined;
  /**
   * @member {module:model/AutomaticTransitionInfoLinks} links
   */
  exports.prototype['links'] = undefined;

  // Implement AutomaticTransition interface:
  /**
   * @member {module:model/BeezUPCommonMarketplaceTechnicalCode} marketplaceTechnicalCode
   */
exports.prototype['marketplaceTechnicalCode'] = undefined;

  /**
   * @member {module:model/AccountId} accountId
   */
exports.prototype['accountId'] = undefined;

  /**
   * @member {Number} orderStatusTransitionId
   */
exports.prototype['orderStatusTransitionId'] = undefined;

  /**
   * @member {Boolean} enabled
   */
exports.prototype['enabled'] = undefined;



  return exports;
}));


