/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.BeezUPCommonSuccessSummary = factory(root.BeezUpApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BeezUPCommonSuccessSummary model module.
   * @module model/BeezUPCommonSuccessSummary
   * @version 2.0
   */

  /**
   * Constructs a new <code>BeezUPCommonSuccessSummary</code>.
   * @alias module:model/BeezUPCommonSuccessSummary
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>BeezUPCommonSuccessSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BeezUPCommonSuccessSummary} obj Optional instance to populate.
   * @return {module:model/BeezUPCommonSuccessSummary} The populated <code>BeezUPCommonSuccessSummary</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('successCode')) {
        obj['successCode'] = ApiClient.convertToType(data['successCode'], 'String');
      }
      if (data.hasOwnProperty('successMessage')) {
        obj['successMessage'] = ApiClient.convertToType(data['successMessage'], 'String');
      }
      if (data.hasOwnProperty('successArguments')) {
        obj['successArguments'] = ApiClient.convertToType(data['successArguments'], {'String': 'String'});
      }
      if (data.hasOwnProperty('propertyName')) {
        obj['propertyName'] = ApiClient.convertToType(data['propertyName'], 'String');
      }
      if (data.hasOwnProperty('propertyValue')) {
        obj['propertyValue'] = ApiClient.convertToType(data['propertyValue'], 'String');
      }
      if (data.hasOwnProperty('objectName')) {
        obj['objectName'] = ApiClient.convertToType(data['objectName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} successCode
   */
  exports.prototype['successCode'] = undefined;
  /**
   * @member {String} successMessage
   */
  exports.prototype['successMessage'] = undefined;
  /**
   * @member {Object.<String, String>} successArguments
   */
  exports.prototype['successArguments'] = undefined;
  /**
   * @member {String} propertyName
   */
  exports.prototype['propertyName'] = undefined;
  /**
   * @member {String} propertyValue
   */
  exports.prototype['propertyValue'] = undefined;
  /**
   * @member {String} objectName
   */
  exports.prototype['objectName'] = undefined;



  return exports;
}));


