/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.BeezUPCommonLOVLink2 = factory(root.BeezUpApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BeezUPCommonLOVLink2 model module.
   * @module model/BeezUPCommonLOVLink2
   * @version 2.0
   */

  /**
   * Constructs a new <code>BeezUPCommonLOVLink2</code>.
   * Describe the way you have to follow to get access to the LOV
   * @alias module:model/BeezUPCommonLOVLink2
   * @class
   * @param listName {String} The name of the list of value
   */
  var exports = function(listName) {
    var _this = this;



    _this['listName'] = listName;
  };

  /**
   * Constructs a <code>BeezUPCommonLOVLink2</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BeezUPCommonLOVLink2} obj Optional instance to populate.
   * @return {module:model/BeezUPCommonLOVLink2} The populated <code>BeezUPCommonLOVLink2</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('rel')) {
        obj['rel'] = ApiClient.convertToType(data['rel'], 'String');
      }
      if (data.hasOwnProperty('href')) {
        obj['href'] = ApiClient.convertToType(data['href'], 'String');
      }
      if (data.hasOwnProperty('listName')) {
        obj['listName'] = ApiClient.convertToType(data['listName'], 'String');
      }
    }
    return obj;
  }

  /**
   * Indicate the relation name related to the link
   * @member {String} rel
   */
  exports.prototype['rel'] = undefined;
  /**
   * Indicate the relative uri pattern to the list of value
   * @member {String} href
   * @default '/v2/user/{listName}'
   */
  exports.prototype['href'] = '/v2/user/{listName}';
  /**
   * The name of the list of value
   * @member {String} listName
   */
  exports.prototype['listName'] = undefined;



  return exports;
}));


