/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonChannelId', 'model/BeezUPCommonChannelName', 'model/BeezUPCommonHttpUrl'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonChannelId'), require('./BeezUPCommonChannelName'), require('./BeezUPCommonHttpUrl'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.BeezUPCommonChannelBasicInfo = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonChannelId, root.BeezUpApi.BeezUPCommonChannelName, root.BeezUpApi.BeezUPCommonHttpUrl);
  }
}(this, function(ApiClient, BeezUPCommonChannelId, BeezUPCommonChannelName, BeezUPCommonHttpUrl) {
  'use strict';




  /**
   * The BeezUPCommonChannelBasicInfo model module.
   * @module model/BeezUPCommonChannelBasicInfo
   * @version 2.0
   */

  /**
   * Constructs a new <code>BeezUPCommonChannelBasicInfo</code>.
   * The basic info related to a channel
   * @alias module:model/BeezUPCommonChannelBasicInfo
   * @class
   * @param channelId {module:model/BeezUPCommonChannelId} 
   * @param channelName {module:model/BeezUPCommonChannelName} 
   * @param channelImageUrl {module:model/BeezUPCommonHttpUrl} 
   */
  var exports = function(channelId, channelName, channelImageUrl) {
    var _this = this;

    _this['channelId'] = channelId;
    _this['channelName'] = channelName;
    _this['channelImageUrl'] = channelImageUrl;
  };

  /**
   * Constructs a <code>BeezUPCommonChannelBasicInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BeezUPCommonChannelBasicInfo} obj Optional instance to populate.
   * @return {module:model/BeezUPCommonChannelBasicInfo} The populated <code>BeezUPCommonChannelBasicInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('channelId')) {
        obj['channelId'] = BeezUPCommonChannelId.constructFromObject(data['channelId']);
      }
      if (data.hasOwnProperty('channelName')) {
        obj['channelName'] = BeezUPCommonChannelName.constructFromObject(data['channelName']);
      }
      if (data.hasOwnProperty('channelImageUrl')) {
        obj['channelImageUrl'] = BeezUPCommonHttpUrl.constructFromObject(data['channelImageUrl']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BeezUPCommonChannelId} channelId
   */
  exports.prototype['channelId'] = undefined;
  /**
   * @member {module:model/BeezUPCommonChannelName} channelName
   */
  exports.prototype['channelName'] = undefined;
  /**
   * @member {module:model/BeezUPCommonHttpUrl} channelImageUrl
   */
  exports.prototype['channelImageUrl'] = undefined;



  return exports;
}));


