/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonHref', 'model/BeezUPCommonHttpMethod', 'model/BeezUPCommonInfoSummaries', 'model/BeezUPCommonLinkParameter2', 'model/BeezUPCommonOperationId'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonHref'), require('./BeezUPCommonHttpMethod'), require('./BeezUPCommonInfoSummaries'), require('./BeezUPCommonLinkParameter2'), require('./BeezUPCommonOperationId'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.BeezUPCommonLink2 = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonHref, root.BeezUpApi.BeezUPCommonHttpMethod, root.BeezUpApi.BeezUPCommonInfoSummaries, root.BeezUpApi.BeezUPCommonLinkParameter2, root.BeezUpApi.BeezUPCommonOperationId);
  }
}(this, function(ApiClient, BeezUPCommonHref, BeezUPCommonHttpMethod, BeezUPCommonInfoSummaries, BeezUPCommonLinkParameter2, BeezUPCommonOperationId) {
  'use strict';




  /**
   * The BeezUPCommonLink2 model module.
   * @module model/BeezUPCommonLink2
   * @version 2.0
   */

  /**
   * Constructs a new <code>BeezUPCommonLink2</code>.
   * @alias module:model/BeezUPCommonLink2
   * @class
   * @param rel {String} Indicate the relation name related to the link
   */
  var exports = function(rel) {
    var _this = this;

    _this['rel'] = rel;





  };

  /**
   * Constructs a <code>BeezUPCommonLink2</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BeezUPCommonLink2} obj Optional instance to populate.
   * @return {module:model/BeezUPCommonLink2} The populated <code>BeezUPCommonLink2</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('rel')) {
        obj['rel'] = ApiClient.convertToType(data['rel'], 'String');
      }
      if (data.hasOwnProperty('href')) {
        obj['href'] = BeezUPCommonHref.constructFromObject(data['href']);
      }
      if (data.hasOwnProperty('operationId')) {
        obj['operationId'] = BeezUPCommonOperationId.constructFromObject(data['operationId']);
      }
      if (data.hasOwnProperty('method')) {
        obj['method'] = BeezUPCommonHttpMethod.constructFromObject(data['method']);
      }
      if (data.hasOwnProperty('parameters')) {
        obj['parameters'] = ApiClient.convertToType(data['parameters'], [BeezUPCommonLinkParameter2]);
      }
      if (data.hasOwnProperty('info')) {
        obj['info'] = BeezUPCommonInfoSummaries.constructFromObject(data['info']);
      }
    }
    return obj;
  }

  /**
   * Indicate the relation name related to the link
   * @member {String} rel
   */
  exports.prototype['rel'] = undefined;
  /**
   * @member {module:model/BeezUPCommonHref} href
   */
  exports.prototype['href'] = undefined;
  /**
   * @member {module:model/BeezUPCommonOperationId} operationId
   */
  exports.prototype['operationId'] = undefined;
  /**
   * @member {module:model/BeezUPCommonHttpMethod} method
   */
  exports.prototype['method'] = undefined;
  /**
   * @member {Array.<module:model/BeezUPCommonLinkParameter2>} parameters
   */
  exports.prototype['parameters'] = undefined;
  /**
   * @member {module:model/BeezUPCommonInfoSummaries} info
   */
  exports.prototype['info'] = undefined;



  return exports;
}));


