/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonLink3'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonLink3'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.BeezUPCommonPaginationResultLinks = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonLink3);
  }
}(this, function(ApiClient, BeezUPCommonLink3) {
  'use strict';




  /**
   * The BeezUPCommonPaginationResultLinks model module.
   * @module model/BeezUPCommonPaginationResultLinks
   * @version 2.0
   */

  /**
   * Constructs a new <code>BeezUPCommonPaginationResultLinks</code>.
   * The navigation links &#39;first&#39;, &#39;last&#39;, &#39;next&#39;, &#39;previous&#39;
   * @alias module:model/BeezUPCommonPaginationResultLinks
   * @class
   * @param first {module:model/BeezUPCommonLink3} 
   * @param last {module:model/BeezUPCommonLink3} 
   */
  var exports = function(first, last) {
    var _this = this;

    _this['first'] = first;
    _this['last'] = last;


  };

  /**
   * Constructs a <code>BeezUPCommonPaginationResultLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BeezUPCommonPaginationResultLinks} obj Optional instance to populate.
   * @return {module:model/BeezUPCommonPaginationResultLinks} The populated <code>BeezUPCommonPaginationResultLinks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('first')) {
        obj['first'] = BeezUPCommonLink3.constructFromObject(data['first']);
      }
      if (data.hasOwnProperty('last')) {
        obj['last'] = BeezUPCommonLink3.constructFromObject(data['last']);
      }
      if (data.hasOwnProperty('previous')) {
        obj['previous'] = BeezUPCommonLink3.constructFromObject(data['previous']);
      }
      if (data.hasOwnProperty('next')) {
        obj['next'] = BeezUPCommonLink3.constructFromObject(data['next']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BeezUPCommonLink3} first
   */
  exports.prototype['first'] = undefined;
  /**
   * @member {module:model/BeezUPCommonLink3} last
   */
  exports.prototype['last'] = undefined;
  /**
   * @member {module:model/BeezUPCommonLink3} previous
   */
  exports.prototype['previous'] = undefined;
  /**
   * @member {module:model/BeezUPCommonLink3} next
   */
  exports.prototype['next'] = undefined;



  return exports;
}));


