/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.BeezUPCommonProductBasicInfo = factory(root.BeezUpApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BeezUPCommonProductBasicInfo model module.
   * @module model/BeezUPCommonProductBasicInfo
   * @version 2.0
   */

  /**
   * Constructs a new <code>BeezUPCommonProductBasicInfo</code>.
   * The basic information related to a product
   * @alias module:model/BeezUPCommonProductBasicInfo
   * @class
   * @param productId {String} The product identifier
   * @param productSku {String} The product SKU
   * @param productTitle {String} The product tile
   * @param productImageUrl {String} The product image Url
   * @param productActive {Boolean} Indicates if the product still exists in your catalog
   */
  var exports = function(productId, productSku, productTitle, productImageUrl, productActive) {
    var _this = this;

    _this['productId'] = productId;
    _this['productSku'] = productSku;
    _this['productTitle'] = productTitle;
    _this['productImageUrl'] = productImageUrl;
    _this['productActive'] = productActive;
  };

  /**
   * Constructs a <code>BeezUPCommonProductBasicInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BeezUPCommonProductBasicInfo} obj Optional instance to populate.
   * @return {module:model/BeezUPCommonProductBasicInfo} The populated <code>BeezUPCommonProductBasicInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('productId')) {
        obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
      }
      if (data.hasOwnProperty('productSku')) {
        obj['productSku'] = ApiClient.convertToType(data['productSku'], 'String');
      }
      if (data.hasOwnProperty('productTitle')) {
        obj['productTitle'] = ApiClient.convertToType(data['productTitle'], 'String');
      }
      if (data.hasOwnProperty('productImageUrl')) {
        obj['productImageUrl'] = ApiClient.convertToType(data['productImageUrl'], 'String');
      }
      if (data.hasOwnProperty('productActive')) {
        obj['productActive'] = ApiClient.convertToType(data['productActive'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * The product identifier
   * @member {String} productId
   */
  exports.prototype['productId'] = undefined;
  /**
   * The product SKU
   * @member {String} productSku
   */
  exports.prototype['productSku'] = undefined;
  /**
   * The product tile
   * @member {String} productTitle
   */
  exports.prototype['productTitle'] = undefined;
  /**
   * The product image Url
   * @member {String} productImageUrl
   */
  exports.prototype['productImageUrl'] = undefined;
  /**
   * Indicates if the product still exists in your catalog
   * @member {Boolean} productActive
   */
  exports.prototype['productActive'] = undefined;



  return exports;
}));


