/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BillingPeriod'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BillingPeriod'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.BillingPeriods = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BillingPeriod);
  }
}(this, function(ApiClient, BillingPeriod) {
  'use strict';




  /**
   * The BillingPeriods model module.
   * @module model/BillingPeriods
   * @version 2.0
   */

  /**
   * Constructs a new <code>BillingPeriods</code>.
   * @alias module:model/BillingPeriods
   * @class
   * @param billingPeriods {Array.<module:model/BillingPeriod>} The billing period list
   */
  var exports = function(billingPeriods) {
    var _this = this;

    _this['billingPeriods'] = billingPeriods;
  };

  /**
   * Constructs a <code>BillingPeriods</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BillingPeriods} obj Optional instance to populate.
   * @return {module:model/BillingPeriods} The populated <code>BillingPeriods</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('billingPeriods')) {
        obj['billingPeriods'] = ApiClient.convertToType(data['billingPeriods'], [BillingPeriod]);
      }
    }
    return obj;
  }

  /**
   * The billing period list
   * @member {Array.<module:model/BillingPeriod>} billingPeriods
   */
  exports.prototype['billingPeriods'] = undefined;



  return exports;
}));


