/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BonusType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BonusType'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.BonusInfo = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BonusType);
  }
}(this, function(ApiClient, BonusType) {
  'use strict';




  /**
   * The BonusInfo model module.
   * @module model/BonusInfo
   * @version 2.0
   */

  /**
   * Constructs a new <code>BonusInfo</code>.
   * @alias module:model/BonusInfo
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>BonusInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BonusInfo} obj Optional instance to populate.
   * @return {module:model/BonusInfo} The populated <code>BonusInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('bonusType')) {
        obj['bonusType'] = BonusType.constructFromObject(data['bonusType']);
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BonusType} bonusType
   */
  exports.prototype['bonusType'] = undefined;
  /**
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;



  return exports;
}));


