/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CategoryMappingStatus'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CategoryMappingStatus'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.CategoryMappingState = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.CategoryMappingStatus);
  }
}(this, function(ApiClient, CategoryMappingStatus) {
  'use strict';




  /**
   * The CategoryMappingState model module.
   * @module model/CategoryMappingState
   * @version 2.0
   */

  /**
   * Constructs a new <code>CategoryMappingState</code>.
   * The category mapping state of the channel catalog
   * @alias module:model/CategoryMappingState
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>CategoryMappingState</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CategoryMappingState} obj Optional instance to populate.
   * @return {module:model/CategoryMappingState} The populated <code>CategoryMappingState</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('status')) {
        obj['status'] = CategoryMappingStatus.constructFromObject(data['status']);
      }
      if (data.hasOwnProperty('uncategorizedProductCount')) {
        obj['uncategorizedProductCount'] = ApiClient.convertToType(data['uncategorizedProductCount'], 'Number');
      }
      if (data.hasOwnProperty('categorizedWithoutCostProductCount')) {
        obj['categorizedWithoutCostProductCount'] = ApiClient.convertToType(data['categorizedWithoutCostProductCount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/CategoryMappingStatus} status
   */
  exports.prototype['status'] = undefined;
  /**
   * Indicates the uncategorized product count
   * @member {Number} uncategorizedProductCount
   */
  exports.prototype['uncategorizedProductCount'] = undefined;
  /**
   * Indicates the categorized product count without cost defined on the category
   * @member {Number} categorizedWithoutCostProductCount
   */
  exports.prototype['categorizedWithoutCostProductCount'] = undefined;



  return exports;
}));


