/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChannelCatalogProductInfo', 'model/ChannelCatalogProductInfoListLinks'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChannelCatalogProductInfo'), require('./ChannelCatalogProductInfoListLinks'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ChannelCatalogProductInfoList = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.ChannelCatalogProductInfo, root.BeezUpApi.ChannelCatalogProductInfoListLinks);
  }
}(this, function(ApiClient, ChannelCatalogProductInfo, ChannelCatalogProductInfoListLinks) {
  'use strict';




  /**
   * The ChannelCatalogProductInfoList model module.
   * @module model/ChannelCatalogProductInfoList
   * @version 2.0
   */

  /**
   * Constructs a new <code>ChannelCatalogProductInfoList</code>.
   * The channel catalog product info list
   * @alias module:model/ChannelCatalogProductInfoList
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ChannelCatalogProductInfoList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelCatalogProductInfoList} obj Optional instance to populate.
   * @return {module:model/ChannelCatalogProductInfoList} The populated <code>ChannelCatalogProductInfoList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ChannelCatalogProductInfoListLinks.constructFromObject(data['links']);
      }
      if (data.hasOwnProperty('productInfos')) {
        obj['productInfos'] = ApiClient.convertToType(data['productInfos'], [ChannelCatalogProductInfo]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ChannelCatalogProductInfoListLinks} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Array.<module:model/ChannelCatalogProductInfo>} productInfos
   */
  exports.prototype['productInfos'] = undefined;



  return exports;
}));


