/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChannelInfo', 'model/ChannelInfoListLinks'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChannelInfo'), require('./ChannelInfoListLinks'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ChannelInfoList = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.ChannelInfo, root.BeezUpApi.ChannelInfoListLinks);
  }
}(this, function(ApiClient, ChannelInfo, ChannelInfoListLinks) {
  'use strict';




  /**
   * The ChannelInfoList model module.
   * @module model/ChannelInfoList
   * @version 2.0
   */

  /**
   * Constructs a new <code>ChannelInfoList</code>.
   * @alias module:model/ChannelInfoList
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ChannelInfoList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelInfoList} obj Optional instance to populate.
   * @return {module:model/ChannelInfoList} The populated <code>ChannelInfoList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ChannelInfoListLinks.constructFromObject(data['links']);
      }
      if (data.hasOwnProperty('channels')) {
        obj['channels'] = ApiClient.convertToType(data['channels'], [ChannelInfo]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ChannelInfoListLinks} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Array.<module:model/ChannelInfo>} channels
   */
  exports.prototype['channels'] = undefined;



  return exports;
}));


