/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonCatalogCategoryPath', 'model/BeezUPCommonChannelCategoryPath', 'model/BeezUPCommonLink2', 'model/ChannelCatalogCategoryMapping'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonCatalogCategoryPath'), require('./BeezUPCommonChannelCategoryPath'), require('./BeezUPCommonLink2'), require('./ChannelCatalogCategoryMapping'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ChannelCatalogCategoryMappingInfo = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonCatalogCategoryPath, root.BeezUpApi.BeezUPCommonChannelCategoryPath, root.BeezUpApi.BeezUPCommonLink2, root.BeezUpApi.ChannelCatalogCategoryMapping);
  }
}(this, function(ApiClient, BeezUPCommonCatalogCategoryPath, BeezUPCommonChannelCategoryPath, BeezUPCommonLink2, ChannelCatalogCategoryMapping) {
  'use strict';




  /**
   * The ChannelCatalogCategoryMappingInfo model module.
   * @module model/ChannelCatalogCategoryMappingInfo
   * @version 2.0
   */

  /**
   * Constructs a new <code>ChannelCatalogCategoryMappingInfo</code>.
   * @alias module:model/ChannelCatalogCategoryMappingInfo
   * @class
   * @implements module:model/ChannelCatalogCategoryMapping
   * @param catalogCategoryPath {module:model/BeezUPCommonCatalogCategoryPath} 
   * @param channelCategoryPath {module:model/BeezUPCommonChannelCategoryPath} 
   * @param links {Array.<module:model/BeezUPCommonLink2>} 
   */
  var exports = function(catalogCategoryPath, channelCategoryPath, links) {
    var _this = this;

    ChannelCatalogCategoryMapping.call(_this, catalogCategoryPath, channelCategoryPath);
    _this['links'] = links;
  };

  /**
   * Constructs a <code>ChannelCatalogCategoryMappingInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelCatalogCategoryMappingInfo} obj Optional instance to populate.
   * @return {module:model/ChannelCatalogCategoryMappingInfo} The populated <code>ChannelCatalogCategoryMappingInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      ChannelCatalogCategoryMapping.constructFromObject(data, obj);
      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [BeezUPCommonLink2]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/BeezUPCommonLink2>} links
   */
  exports.prototype['links'] = undefined;

  // Implement ChannelCatalogCategoryMapping interface:
  /**
   * @member {module:model/BeezUPCommonCatalogCategoryPath} catalogCategoryPath
   */
exports.prototype['catalogCategoryPath'] = undefined;

  /**
   * @member {module:model/BeezUPCommonChannelCategoryPath} channelCategoryPath
   */
exports.prototype['channelCategoryPath'] = undefined;

  /**
   * In case of CPC_ByCategory or CPA_ByCategory cost type, you have to indicate the cost value.
   * @member {Number} costValue
   */
exports.prototype['costValue'] = undefined;



  return exports;
}));


