/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonCatalogCategoryPath', 'model/BeezUPCommonChannelCategoryPath'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonCatalogCategoryPath'), require('./BeezUPCommonChannelCategoryPath'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ChannelCatalogCategoryMapping = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonCatalogCategoryPath, root.BeezUpApi.BeezUPCommonChannelCategoryPath);
  }
}(this, function(ApiClient, BeezUPCommonCatalogCategoryPath, BeezUPCommonChannelCategoryPath) {
  'use strict';




  /**
   * The ChannelCatalogCategoryMapping model module.
   * @module model/ChannelCatalogCategoryMapping
   * @version 2.0
   */

  /**
   * Constructs a new <code>ChannelCatalogCategoryMapping</code>.
   * Represent a mapping between a catalog category path and a channel category path.  The cost on this mapping can be applied. 
   * @alias module:model/ChannelCatalogCategoryMapping
   * @class
   * @param catalogCategoryPath {module:model/BeezUPCommonCatalogCategoryPath} 
   * @param channelCategoryPath {module:model/BeezUPCommonChannelCategoryPath} 
   */
  var exports = function(catalogCategoryPath, channelCategoryPath) {
    var _this = this;

    _this['catalogCategoryPath'] = catalogCategoryPath;
    _this['channelCategoryPath'] = channelCategoryPath;

  };

  /**
   * Constructs a <code>ChannelCatalogCategoryMapping</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelCatalogCategoryMapping} obj Optional instance to populate.
   * @return {module:model/ChannelCatalogCategoryMapping} The populated <code>ChannelCatalogCategoryMapping</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('catalogCategoryPath')) {
        obj['catalogCategoryPath'] = BeezUPCommonCatalogCategoryPath.constructFromObject(data['catalogCategoryPath']);
      }
      if (data.hasOwnProperty('channelCategoryPath')) {
        obj['channelCategoryPath'] = BeezUPCommonChannelCategoryPath.constructFromObject(data['channelCategoryPath']);
      }
      if (data.hasOwnProperty('costValue')) {
        obj['costValue'] = ApiClient.convertToType(data['costValue'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BeezUPCommonCatalogCategoryPath} catalogCategoryPath
   */
  exports.prototype['catalogCategoryPath'] = undefined;
  /**
   * @member {module:model/BeezUPCommonChannelCategoryPath} channelCategoryPath
   */
  exports.prototype['channelCategoryPath'] = undefined;
  /**
   * In case of CPC_ByCategory or CPA_ByCategory cost type, you have to indicate the cost value.
   * @member {Number} costValue
   */
  exports.prototype['costValue'] = undefined;



  return exports;
}));


