/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LinksGetChannelCatalogMarketplacePropertiesLink', 'model/LinksGetChannelCatalogMarketplaceSettingsLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LinksGetChannelCatalogMarketplacePropertiesLink'), require('./LinksGetChannelCatalogMarketplaceSettingsLink'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ChannelCatalogMarketplacePropertiesLinks = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.LinksGetChannelCatalogMarketplacePropertiesLink, root.BeezUpApi.LinksGetChannelCatalogMarketplaceSettingsLink);
  }
}(this, function(ApiClient, LinksGetChannelCatalogMarketplacePropertiesLink, LinksGetChannelCatalogMarketplaceSettingsLink) {
  'use strict';




  /**
   * The ChannelCatalogMarketplacePropertiesLinks model module.
   * @module model/ChannelCatalogMarketplacePropertiesLinks
   * @version 2.0
   */

  /**
   * Constructs a new <code>ChannelCatalogMarketplacePropertiesLinks</code>.
   * @alias module:model/ChannelCatalogMarketplacePropertiesLinks
   * @class
   * @param self {module:model/LinksGetChannelCatalogMarketplacePropertiesLink} 
   * @param settings {module:model/LinksGetChannelCatalogMarketplaceSettingsLink} 
   */
  var exports = function(self, settings) {
    var _this = this;

    _this['self'] = self;
    _this['settings'] = settings;
  };

  /**
   * Constructs a <code>ChannelCatalogMarketplacePropertiesLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelCatalogMarketplacePropertiesLinks} obj Optional instance to populate.
   * @return {module:model/ChannelCatalogMarketplacePropertiesLinks} The populated <code>ChannelCatalogMarketplacePropertiesLinks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('self')) {
        obj['self'] = LinksGetChannelCatalogMarketplacePropertiesLink.constructFromObject(data['self']);
      }
      if (data.hasOwnProperty('settings')) {
        obj['settings'] = LinksGetChannelCatalogMarketplaceSettingsLink.constructFromObject(data['settings']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/LinksGetChannelCatalogMarketplacePropertiesLink} self
   */
  exports.prototype['self'] = undefined;
  /**
   * @member {module:model/LinksGetChannelCatalogMarketplaceSettingsLink} settings
   */
  exports.prototype['settings'] = undefined;



  return exports;
}));


