/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonChannelCategoryId', 'model/ChannelCategory', 'model/ChannelCategoryChannelCode', 'model/ChannelCategoryColumnOverrides', 'model/ChannelCategoryDefaultCost', 'model/ChannelCategoryLevel'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonChannelCategoryId'), require('./ChannelCategory'), require('./ChannelCategoryChannelCode'), require('./ChannelCategoryColumnOverrides'), require('./ChannelCategoryDefaultCost'), require('./ChannelCategoryLevel'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ChannelFirstLevelCategory = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonChannelCategoryId, root.BeezUpApi.ChannelCategory, root.BeezUpApi.ChannelCategoryChannelCode, root.BeezUpApi.ChannelCategoryColumnOverrides, root.BeezUpApi.ChannelCategoryDefaultCost, root.BeezUpApi.ChannelCategoryLevel);
  }
}(this, function(ApiClient, BeezUPCommonChannelCategoryId, ChannelCategory, ChannelCategoryChannelCode, ChannelCategoryColumnOverrides, ChannelCategoryDefaultCost, ChannelCategoryLevel) {
  'use strict';




  /**
   * The ChannelFirstLevelCategory model module.
   * @module model/ChannelFirstLevelCategory
   * @version 2.0
   */

  /**
   * Constructs a new <code>ChannelFirstLevelCategory</code>.
   * The first level category with his sub categories
   * @alias module:model/ChannelFirstLevelCategory
   * @class
   * @param channelCategoryId {module:model/BeezUPCommonChannelCategoryId} 
   * @param channelCategoryName {String} The channel category name
   * @param channelCategoryLevel {module:model/ChannelCategoryLevel} 
   */
  var exports = function(channelCategoryId, channelCategoryName, channelCategoryLevel) {
    var _this = this;

    _this['channelCategoryId'] = channelCategoryId;
    _this['channelCategoryName'] = channelCategoryName;
    _this['channelCategoryLevel'] = channelCategoryLevel;




  };

  /**
   * Constructs a <code>ChannelFirstLevelCategory</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelFirstLevelCategory} obj Optional instance to populate.
   * @return {module:model/ChannelFirstLevelCategory} The populated <code>ChannelFirstLevelCategory</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('channelCategoryId')) {
        obj['channelCategoryId'] = BeezUPCommonChannelCategoryId.constructFromObject(data['channelCategoryId']);
      }
      if (data.hasOwnProperty('channelCategoryName')) {
        obj['channelCategoryName'] = ApiClient.convertToType(data['channelCategoryName'], 'String');
      }
      if (data.hasOwnProperty('channelCategoryLevel')) {
        obj['channelCategoryLevel'] = ChannelCategoryLevel.constructFromObject(data['channelCategoryLevel']);
      }
      if (data.hasOwnProperty('channelCategoryDefaultCost')) {
        obj['channelCategoryDefaultCost'] = ChannelCategoryDefaultCost.constructFromObject(data['channelCategoryDefaultCost']);
      }
      if (data.hasOwnProperty('channelCategoryChannelCode')) {
        obj['channelCategoryChannelCode'] = ChannelCategoryChannelCode.constructFromObject(data['channelCategoryChannelCode']);
      }
      if (data.hasOwnProperty('channelCategoryColumnOverrides')) {
        obj['channelCategoryColumnOverrides'] = ChannelCategoryColumnOverrides.constructFromObject(data['channelCategoryColumnOverrides']);
      }
      if (data.hasOwnProperty('subCategories')) {
        obj['subCategories'] = ApiClient.convertToType(data['subCategories'], [ChannelCategory]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BeezUPCommonChannelCategoryId} channelCategoryId
   */
  exports.prototype['channelCategoryId'] = undefined;
  /**
   * The channel category name
   * @member {String} channelCategoryName
   */
  exports.prototype['channelCategoryName'] = undefined;
  /**
   * @member {module:model/ChannelCategoryLevel} channelCategoryLevel
   */
  exports.prototype['channelCategoryLevel'] = undefined;
  /**
   * @member {module:model/ChannelCategoryDefaultCost} channelCategoryDefaultCost
   */
  exports.prototype['channelCategoryDefaultCost'] = undefined;
  /**
   * @member {module:model/ChannelCategoryChannelCode} channelCategoryChannelCode
   */
  exports.prototype['channelCategoryChannelCode'] = undefined;
  /**
   * @member {module:model/ChannelCategoryColumnOverrides} channelCategoryColumnOverrides
   */
  exports.prototype['channelCategoryColumnOverrides'] = undefined;
  /**
   * @member {Array.<module:model/ChannelCategory>} subCategories
   */
  exports.prototype['subCategories'] = undefined;



  return exports;
}));


