/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonLink2', 'model/ChannelCatalog'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonLink2'), require('./ChannelCatalog'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ChannelCatalogList = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonLink2, root.BeezUpApi.ChannelCatalog);
  }
}(this, function(ApiClient, BeezUPCommonLink2, ChannelCatalog) {
  'use strict';




  /**
   * The ChannelCatalogList model module.
   * @module model/ChannelCatalogList
   * @version 2.0
   */

  /**
   * Constructs a new <code>ChannelCatalogList</code>.
   * @alias module:model/ChannelCatalogList
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ChannelCatalogList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelCatalogList} obj Optional instance to populate.
   * @return {module:model/ChannelCatalogList} The populated <code>ChannelCatalogList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [BeezUPCommonLink2]);
      }
      if (data.hasOwnProperty('channelCatalogs')) {
        obj['channelCatalogs'] = ApiClient.convertToType(data['channelCatalogs'], [ChannelCatalog]);
      }
    }
    return obj;
  }

  /**
   * Indicates how to create a channel catalog and how to get the channel catalog list
   * @member {Array.<module:model/BeezUPCommonLink2>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Array.<module:model/ChannelCatalog>} channelCatalogs
   */
  exports.prototype['channelCatalogs'] = undefined;



  return exports;
}));


