/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChannelCatalogProductInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChannelCatalogProductInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ChannelCatalogProductByChannelCatalogResponse = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.ChannelCatalogProductInfo);
  }
}(this, function(ApiClient, ChannelCatalogProductInfo) {
  'use strict';




  /**
   * The ChannelCatalogProductByChannelCatalogResponse model module.
   * @module model/ChannelCatalogProductByChannelCatalogResponse
   * @version 2.0
   */

  /**
   * Constructs a new <code>ChannelCatalogProductByChannelCatalogResponse</code>.
   * @alias module:model/ChannelCatalogProductByChannelCatalogResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ChannelCatalogProductByChannelCatalogResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelCatalogProductByChannelCatalogResponse} obj Optional instance to populate.
   * @return {module:model/ChannelCatalogProductByChannelCatalogResponse} The populated <code>ChannelCatalogProductByChannelCatalogResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('channelCatalogs')) {
        obj['channelCatalogs'] = ApiClient.convertToType(data['channelCatalogs'], {'String': ChannelCatalogProductInfo});
      }
    }
    return obj;
  }

  /**
   * The channel catalog product by channel catalog. The key is the channel catalog identifier
   * @member {Object.<String, module:model/ChannelCatalogProductInfo>} channelCatalogs
   */
  exports.prototype['channelCatalogs'] = undefined;



  return exports;
}));


