/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ChannelCatalogExportationReporting = factory(root.BeezUpApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ChannelCatalogExportationReporting model module.
   * @module model/ChannelCatalogExportationReporting
   * @version 2.0
   */

  /**
   * Constructs a new <code>ChannelCatalogExportationReporting</code>.
   * @alias module:model/ChannelCatalogExportationReporting
   * @class
   * @param exportationUtcDate {Date} The exportation UTC date
   * @param clientIpAddress {String} The IP address of the client who requests this exportation
   * @param clientUserAgent {String} The http header User-Agent sent by the client who requests this operation
   */
  var exports = function(exportationUtcDate, clientIpAddress, clientUserAgent) {
    var _this = this;

    _this['exportationUtcDate'] = exportationUtcDate;



    _this['clientIpAddress'] = clientIpAddress;
    _this['clientUserAgent'] = clientUserAgent;
  };

  /**
   * Constructs a <code>ChannelCatalogExportationReporting</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelCatalogExportationReporting} obj Optional instance to populate.
   * @return {module:model/ChannelCatalogExportationReporting} The populated <code>ChannelCatalogExportationReporting</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('exportationUtcDate')) {
        obj['exportationUtcDate'] = ApiClient.convertToType(data['exportationUtcDate'], 'Date');
      }
      if (data.hasOwnProperty('exportationDuration')) {
        obj['exportationDuration'] = ApiClient.convertToType(data['exportationDuration'], 'String');
      }
      if (data.hasOwnProperty('cacheStatus')) {
        obj['cacheStatus'] = ApiClient.convertToType(data['cacheStatus'], 'String');
      }
      if (data.hasOwnProperty('exportedProductCount')) {
        obj['exportedProductCount'] = ApiClient.convertToType(data['exportedProductCount'], 'Number');
      }
      if (data.hasOwnProperty('clientIpAddress')) {
        obj['clientIpAddress'] = ApiClient.convertToType(data['clientIpAddress'], 'String');
      }
      if (data.hasOwnProperty('clientUserAgent')) {
        obj['clientUserAgent'] = ApiClient.convertToType(data['clientUserAgent'], 'String');
      }
    }
    return obj;
  }

  /**
   * The exportation UTC date
   * @member {Date} exportationUtcDate
   */
  exports.prototype['exportationUtcDate'] = undefined;
  /**
   * The exportation duration. \\ '00:01:00' measn 1 minute. 
   * @member {String} exportationDuration
   */
  exports.prototype['exportationDuration'] = undefined;
  /**
   * The cache status during the exportation
   * @member {module:model/ChannelCatalogExportationReporting.CacheStatusEnum} cacheStatus
   */
  exports.prototype['cacheStatus'] = undefined;
  /**
   * The exportated product count during this exportation
   * @member {Number} exportedProductCount
   */
  exports.prototype['exportedProductCount'] = undefined;
  /**
   * The IP address of the client who requests this exportation
   * @member {String} clientIpAddress
   */
  exports.prototype['clientIpAddress'] = undefined;
  /**
   * The http header User-Agent sent by the client who requests this operation
   * @member {String} clientUserAgent
   */
  exports.prototype['clientUserAgent'] = undefined;


  /**
   * Allowed values for the <code>cacheStatus</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CacheStatusEnum = {
    /**
     * value: "Error"
     * @const
     */
    "Error": "Error",
    /**
     * value: "Available"
     * @const
     */
    "Available": "Available",
    /**
     * value: "GeneratedManually"
     * @const
     */
    "GeneratedManually": "GeneratedManually"  };


  return exports;
}));


