/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonBeezUPColumnName', 'model/BeezUPCommonColumnDataType', 'model/BeezUPCommonColumnImportance'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonBeezUPColumnName'), require('./BeezUPCommonColumnDataType'), require('./BeezUPCommonColumnImportance'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ChannelColumnConfiguration = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonBeezUPColumnName, root.BeezUpApi.BeezUPCommonColumnDataType, root.BeezUpApi.BeezUPCommonColumnImportance);
  }
}(this, function(ApiClient, BeezUPCommonBeezUPColumnName, BeezUPCommonColumnDataType, BeezUPCommonColumnImportance) {
  'use strict';




  /**
   * The ChannelColumnConfiguration model module.
   * @module model/ChannelColumnConfiguration
   * @version 2.0
   */

  /**
   * Constructs a new <code>ChannelColumnConfiguration</code>.
   * The channel column configuration. The BeezUP Column Name is optional. If the BeezUP column is mapped we will indicate the data type and column importance of the BeezUP column.
   * @alias module:model/ChannelColumnConfiguration
   * @class
   * @param columnImportance {module:model/BeezUPCommonColumnImportance} 
   * @param columnDataType {module:model/BeezUPCommonColumnDataType} 
   */
  var exports = function(columnImportance, columnDataType) {
    var _this = this;

    _this['columnImportance'] = columnImportance;
    _this['columnDataType'] = columnDataType;

  };

  /**
   * Constructs a <code>ChannelColumnConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelColumnConfiguration} obj Optional instance to populate.
   * @return {module:model/ChannelColumnConfiguration} The populated <code>ChannelColumnConfiguration</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('columnImportance')) {
        obj['columnImportance'] = BeezUPCommonColumnImportance.constructFromObject(data['columnImportance']);
      }
      if (data.hasOwnProperty('columnDataType')) {
        obj['columnDataType'] = BeezUPCommonColumnDataType.constructFromObject(data['columnDataType']);
      }
      if (data.hasOwnProperty('beezUPColumnName')) {
        obj['beezUPColumnName'] = BeezUPCommonBeezUPColumnName.constructFromObject(data['beezUPColumnName']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BeezUPCommonColumnImportance} columnImportance
   */
  exports.prototype['columnImportance'] = undefined;
  /**
   * @member {module:model/BeezUPCommonColumnDataType} columnDataType
   */
  exports.prototype['columnDataType'] = undefined;
  /**
   * @member {module:model/BeezUPCommonBeezUPColumnName} beezUPColumnName
   */
  exports.prototype['beezUPColumnName'] = undefined;



  return exports;
}));


