/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountingEmails', 'model/Address', 'model/BeezUPCommonCountryIsoCodeAlpha3', 'model/City', 'model/Company', 'model/PostalCode', 'model/VatNumber'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccountingEmails'), require('./Address'), require('./BeezUPCommonCountryIsoCodeAlpha3'), require('./City'), require('./Company'), require('./PostalCode'), require('./VatNumber'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.CompanyInfo = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.AccountingEmails, root.BeezUpApi.Address, root.BeezUpApi.BeezUPCommonCountryIsoCodeAlpha3, root.BeezUpApi.City, root.BeezUpApi.Company, root.BeezUpApi.PostalCode, root.BeezUpApi.VatNumber);
  }
}(this, function(ApiClient, AccountingEmails, Address, BeezUPCommonCountryIsoCodeAlpha3, City, Company, PostalCode, VatNumber) {
  'use strict';




  /**
   * The CompanyInfo model module.
   * @module model/CompanyInfo
   * @version 2.0
   */

  /**
   * Constructs a new <code>CompanyInfo</code>.
   * @alias module:model/CompanyInfo
   * @class
   * @param address {module:model/Address} 
   * @param postalCode {module:model/PostalCode} 
   * @param city {module:model/City} 
   * @param countryIsoCodeAlpha3 {module:model/BeezUPCommonCountryIsoCodeAlpha3} 
   * @param company {module:model/Company} 
   */
  var exports = function(address, postalCode, city, countryIsoCodeAlpha3, company) {
    var _this = this;

    _this['address'] = address;
    _this['postalCode'] = postalCode;
    _this['city'] = city;
    _this['countryIsoCodeAlpha3'] = countryIsoCodeAlpha3;
    _this['company'] = company;


  };

  /**
   * Constructs a <code>CompanyInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompanyInfo} obj Optional instance to populate.
   * @return {module:model/CompanyInfo} The populated <code>CompanyInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('address')) {
        obj['address'] = Address.constructFromObject(data['address']);
      }
      if (data.hasOwnProperty('postalCode')) {
        obj['postalCode'] = PostalCode.constructFromObject(data['postalCode']);
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = City.constructFromObject(data['city']);
      }
      if (data.hasOwnProperty('countryIsoCodeAlpha3')) {
        obj['countryIsoCodeAlpha3'] = BeezUPCommonCountryIsoCodeAlpha3.constructFromObject(data['countryIsoCodeAlpha3']);
      }
      if (data.hasOwnProperty('company')) {
        obj['company'] = Company.constructFromObject(data['company']);
      }
      if (data.hasOwnProperty('vatNumber')) {
        obj['vatNumber'] = VatNumber.constructFromObject(data['vatNumber']);
      }
      if (data.hasOwnProperty('accountingEmails')) {
        obj['accountingEmails'] = AccountingEmails.constructFromObject(data['accountingEmails']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Address} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {module:model/PostalCode} postalCode
   */
  exports.prototype['postalCode'] = undefined;
  /**
   * @member {module:model/City} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {module:model/BeezUPCommonCountryIsoCodeAlpha3} countryIsoCodeAlpha3
   */
  exports.prototype['countryIsoCodeAlpha3'] = undefined;
  /**
   * @member {module:model/Company} company
   */
  exports.prototype['company'] = undefined;
  /**
   * @member {module:model/VatNumber} vatNumber
   */
  exports.prototype['vatNumber'] = undefined;
  /**
   * @member {module:model/AccountingEmails} accountingEmails
   */
  exports.prototype['accountingEmails'] = undefined;



  return exports;
}));


