/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AutomaticTransition'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AutomaticTransition'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ConfigureAutomaticTransitionRequest = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.AutomaticTransition);
  }
}(this, function(ApiClient, AutomaticTransition) {
  'use strict';




  /**
   * The ConfigureAutomaticTransitionRequest model module.
   * @module model/ConfigureAutomaticTransitionRequest
   * @version 2.0
   */

  /**
   * Constructs a new <code>ConfigureAutomaticTransitionRequest</code>.
   * @alias module:model/ConfigureAutomaticTransitionRequest
   * @class
   * @param automaticTransitions {Array.<module:model/AutomaticTransition>} 
   */
  var exports = function(automaticTransitions) {
    var _this = this;

    _this['automaticTransitions'] = automaticTransitions;
  };

  /**
   * Constructs a <code>ConfigureAutomaticTransitionRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConfigureAutomaticTransitionRequest} obj Optional instance to populate.
   * @return {module:model/ConfigureAutomaticTransitionRequest} The populated <code>ConfigureAutomaticTransitionRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('automaticTransitions')) {
        obj['automaticTransitions'] = ApiClient.convertToType(data['automaticTransitions'], [AutomaticTransition]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/AutomaticTransition>} automaticTransitions
   */
  exports.prototype['automaticTransitions'] = undefined;



  return exports;
}));


