/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ConfigureAutoImportIntervalRequest = factory(root.BeezUpApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ConfigureAutoImportIntervalRequest model module.
   * @module model/ConfigureAutoImportIntervalRequest
   * @version 2.0
   */

  /**
   * Constructs a new <code>ConfigureAutoImportIntervalRequest</code>.
   * The message request to configure the auto import interval
   * @alias module:model/ConfigureAutoImportIntervalRequest
   * @class
   * @param interval {String} Indicate the interval in time span. (i.e. \"04:00:00\" for every 4 hours)
   */
  var exports = function(interval) {
    var _this = this;

    _this['interval'] = interval;
  };

  /**
   * Constructs a <code>ConfigureAutoImportIntervalRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConfigureAutoImportIntervalRequest} obj Optional instance to populate.
   * @return {module:model/ConfigureAutoImportIntervalRequest} The populated <code>ConfigureAutoImportIntervalRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('interval')) {
        obj['interval'] = ApiClient.convertToType(data['interval'], 'String');
      }
    }
    return obj;
  }

  /**
   * Indicate the interval in time span. (i.e. \"04:00:00\" for every 4 hours)
   * @member {String} interval
   */
  exports.prototype['interval'] = undefined;



  return exports;
}));


