/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CatalogColumn'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CatalogColumn'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ConfigureCatalogColumnCatalogRequest = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.CatalogColumn);
  }
}(this, function(ApiClient, CatalogColumn) {
  'use strict';




  /**
   * The ConfigureCatalogColumnCatalogRequest model module.
   * @module model/ConfigureCatalogColumnCatalogRequest
   * @version 2.0
   */

  /**
   * Constructs a new <code>ConfigureCatalogColumnCatalogRequest</code>.
   * The request to configure a catalog column
   * @alias module:model/ConfigureCatalogColumnCatalogRequest
   * @class
   * @param catalogColumn {module:model/CatalogColumn} 
   */
  var exports = function(catalogColumn) {
    var _this = this;

    _this['catalogColumn'] = catalogColumn;
  };

  /**
   * Constructs a <code>ConfigureCatalogColumnCatalogRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConfigureCatalogColumnCatalogRequest} obj Optional instance to populate.
   * @return {module:model/ConfigureCatalogColumnCatalogRequest} The populated <code>ConfigureCatalogColumnCatalogRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('catalogColumn')) {
        obj['catalogColumn'] = CatalogColumn.constructFromObject(data['catalogColumn']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/CatalogColumn} catalogColumn
   */
  exports.prototype['catalogColumn'] = undefined;



  return exports;
}));


