/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonCurrencyCode'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonCurrencyCode'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ContractMoneyInfo = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonCurrencyCode);
  }
}(this, function(ApiClient, BeezUPCommonCurrencyCode) {
  'use strict';




  /**
   * The ContractMoneyInfo model module.
   * @module model/ContractMoneyInfo
   * @version 2.0
   */

  /**
   * Constructs a new <code>ContractMoneyInfo</code>.
   * Describe the pricing information related to the offer.
   * @alias module:model/ContractMoneyInfo
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>ContractMoneyInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContractMoneyInfo} obj Optional instance to populate.
   * @return {module:model/ContractMoneyInfo} The populated <code>ContractMoneyInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amountExcludingTaxesAndExcludingCodePromoDiscountIncludingBillingPeriodDiscount')) {
        obj['amountExcludingTaxesAndExcludingCodePromoDiscountIncludingBillingPeriodDiscount'] = ApiClient.convertToType(data['amountExcludingTaxesAndExcludingCodePromoDiscountIncludingBillingPeriodDiscount'], 'Number');
      }
      if (data.hasOwnProperty('amountExcludingTaxesIncludingDiscounts')) {
        obj['amountExcludingTaxesIncludingDiscounts'] = ApiClient.convertToType(data['amountExcludingTaxesIncludingDiscounts'], 'Number');
      }
      if (data.hasOwnProperty('amountTaxesExcludingDiscountIncludingBillingPeriodDiscount')) {
        obj['amountTaxesExcludingDiscountIncludingBillingPeriodDiscount'] = ApiClient.convertToType(data['amountTaxesExcludingDiscountIncludingBillingPeriodDiscount'], 'Number');
      }
      if (data.hasOwnProperty('amountIncludingTaxesExcludingDiscountIncludingBillingPeriodDiscount')) {
        obj['amountIncludingTaxesExcludingDiscountIncludingBillingPeriodDiscount'] = ApiClient.convertToType(data['amountIncludingTaxesExcludingDiscountIncludingBillingPeriodDiscount'], 'Number');
      }
      if (data.hasOwnProperty('currencyCode')) {
        obj['currencyCode'] = BeezUPCommonCurrencyCode.constructFromObject(data['currencyCode']);
      }
      if (data.hasOwnProperty('vatPercent')) {
        obj['vatPercent'] = ApiClient.convertToType(data['vatPercent'], 'Number');
      }
      if (data.hasOwnProperty('amountExcludingTaxesIncludingDiscountsPerMonth')) {
        obj['amountExcludingTaxesIncludingDiscountsPerMonth'] = ApiClient.convertToType(data['amountExcludingTaxesIncludingDiscountsPerMonth'], 'Number');
      }
      if (data.hasOwnProperty('amountExcludingTaxesAndExcludingDiscounts')) {
        obj['amountExcludingTaxesAndExcludingDiscounts'] = ApiClient.convertToType(data['amountExcludingTaxesAndExcludingDiscounts'], 'Number');
      }
      if (data.hasOwnProperty('amountTaxesIncludingDiscounts')) {
        obj['amountTaxesIncludingDiscounts'] = ApiClient.convertToType(data['amountTaxesIncludingDiscounts'], 'Number');
      }
      if (data.hasOwnProperty('amountIncludingTaxesIncludingDiscounts')) {
        obj['amountIncludingTaxesIncludingDiscounts'] = ApiClient.convertToType(data['amountIncludingTaxesIncludingDiscounts'], 'Number');
      }
      if (data.hasOwnProperty('initialOfferFixedPrice')) {
        obj['initialOfferFixedPrice'] = ApiClient.convertToType(data['initialOfferFixedPrice'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The amount excluding taxes and excluding code promo discount including billing period discount.
   * @member {Number} amountExcludingTaxesAndExcludingCodePromoDiscountIncludingBillingPeriodDiscount
   */
  exports.prototype['amountExcludingTaxesAndExcludingCodePromoDiscountIncludingBillingPeriodDiscount'] = undefined;
  /**
   * The amount excluding taxes including discounts.
   * @member {Number} amountExcludingTaxesIncludingDiscounts
   */
  exports.prototype['amountExcludingTaxesIncludingDiscounts'] = undefined;
  /**
   * The taxes excluding discount including billing period discount.
   * @member {Number} amountTaxesExcludingDiscountIncludingBillingPeriodDiscount
   */
  exports.prototype['amountTaxesExcludingDiscountIncludingBillingPeriodDiscount'] = undefined;
  /**
   * The amount including taxes excluding discount including billing period discount.
   * @member {Number} amountIncludingTaxesExcludingDiscountIncludingBillingPeriodDiscount
   */
  exports.prototype['amountIncludingTaxesExcludingDiscountIncludingBillingPeriodDiscount'] = undefined;
  /**
   * @member {module:model/BeezUPCommonCurrencyCode} currencyCode
   */
  exports.prototype['currencyCode'] = undefined;
  /**
   * The VAT percent.
   * @member {Number} vatPercent
   */
  exports.prototype['vatPercent'] = undefined;
  /**
   * The amount excluding taxes including discounts per month.
   * @member {Number} amountExcludingTaxesIncludingDiscountsPerMonth
   */
  exports.prototype['amountExcludingTaxesIncludingDiscountsPerMonth'] = undefined;
  /**
   * The amount excluding taxes and excluding discounts.
   * @member {Number} amountExcludingTaxesAndExcludingDiscounts
   */
  exports.prototype['amountExcludingTaxesAndExcludingDiscounts'] = undefined;
  /**
   * Taxes including discounts.
   * @member {Number} amountTaxesIncludingDiscounts
   */
  exports.prototype['amountTaxesIncludingDiscounts'] = undefined;
  /**
   * The amount including taxes including discounts.
   * @member {Number} amountIncludingTaxesIncludingDiscounts
   */
  exports.prototype['amountIncludingTaxesIncludingDiscounts'] = undefined;
  /**
   * The initial offer fixed price.
   * @member {Number} initialOfferFixedPrice
   */
  exports.prototype['initialOfferFixedPrice'] = undefined;



  return exports;
}));


