/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ContractsLinks', 'model/CurrentContractInfo', 'model/NextContractInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ContractsLinks'), require('./CurrentContractInfo'), require('./NextContractInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.Contracts = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.ContractsLinks, root.BeezUpApi.CurrentContractInfo, root.BeezUpApi.NextContractInfo);
  }
}(this, function(ApiClient, ContractsLinks, CurrentContractInfo, NextContractInfo) {
  'use strict';




  /**
   * The Contracts model module.
   * @module model/Contracts
   * @version 2.0
   */

  /**
   * Constructs a new <code>Contracts</code>.
   * @alias module:model/Contracts
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Contracts</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Contracts} obj Optional instance to populate.
   * @return {module:model/Contracts} The populated <code>Contracts</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = ContractsLinks.constructFromObject(data['links']);
      }
      if (data.hasOwnProperty('current')) {
        obj['current'] = CurrentContractInfo.constructFromObject(data['current']);
      }
      if (data.hasOwnProperty('next')) {
        obj['next'] = NextContractInfo.constructFromObject(data['next']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ContractsLinks} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {module:model/CurrentContractInfo} current
   */
  exports.prototype['current'] = undefined;
  /**
   * @member {module:model/NextContractInfo} next
   */
  exports.prototype['next'] = undefined;



  return exports;
}));


