/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DisplayGroupName', 'model/EncryptedBlocklyExpression', 'model/EncryptedExpression', 'model/UserColumName'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DisplayGroupName'), require('./EncryptedBlocklyExpression'), require('./EncryptedExpression'), require('./UserColumName'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.CreateCustomColumnRequest = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.DisplayGroupName, root.BeezUpApi.EncryptedBlocklyExpression, root.BeezUpApi.EncryptedExpression, root.BeezUpApi.UserColumName);
  }
}(this, function(ApiClient, DisplayGroupName, EncryptedBlocklyExpression, EncryptedExpression, UserColumName) {
  'use strict';




  /**
   * The CreateCustomColumnRequest model module.
   * @module model/CreateCustomColumnRequest
   * @version 2.0
   */

  /**
   * Constructs a new <code>CreateCustomColumnRequest</code>.
   * The request message to create a custom column
   * @alias module:model/CreateCustomColumnRequest
   * @class
   * @param userColumnName {module:model/UserColumName} 
   * @param encryptedExpression {module:model/EncryptedExpression} 
   * @param encryptedBlocklyExpression {module:model/EncryptedBlocklyExpression} 
   * @param displayGroupName {module:model/DisplayGroupName} 
   */
  var exports = function(userColumnName, encryptedExpression, encryptedBlocklyExpression, displayGroupName) {
    var _this = this;

    _this['userColumnName'] = userColumnName;
    _this['encryptedExpression'] = encryptedExpression;
    _this['encryptedBlocklyExpression'] = encryptedBlocklyExpression;
    _this['displayGroupName'] = displayGroupName;
  };

  /**
   * Constructs a <code>CreateCustomColumnRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateCustomColumnRequest} obj Optional instance to populate.
   * @return {module:model/CreateCustomColumnRequest} The populated <code>CreateCustomColumnRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('userColumnName')) {
        obj['userColumnName'] = UserColumName.constructFromObject(data['userColumnName']);
      }
      if (data.hasOwnProperty('encryptedExpression')) {
        obj['encryptedExpression'] = EncryptedExpression.constructFromObject(data['encryptedExpression']);
      }
      if (data.hasOwnProperty('encryptedBlocklyExpression')) {
        obj['encryptedBlocklyExpression'] = EncryptedBlocklyExpression.constructFromObject(data['encryptedBlocklyExpression']);
      }
      if (data.hasOwnProperty('displayGroupName')) {
        obj['displayGroupName'] = DisplayGroupName.constructFromObject(data['displayGroupName']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/UserColumName} userColumnName
   */
  exports.prototype['userColumnName'] = undefined;
  /**
   * @member {module:model/EncryptedExpression} encryptedExpression
   */
  exports.prototype['encryptedExpression'] = undefined;
  /**
   * @member {module:model/EncryptedBlocklyExpression} encryptedBlocklyExpression
   */
  exports.prototype['encryptedBlocklyExpression'] = undefined;
  /**
   * @member {module:model/DisplayGroupName} displayGroupName
   */
  exports.prototype['displayGroupName'] = undefined;



  return exports;
}));


