/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CompareOptions', 'model/DuplicateProductValueStrategy'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CompareOptions'), require('./DuplicateProductValueStrategy'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.DuplicateProductValueConfiguration = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.CompareOptions, root.BeezUpApi.DuplicateProductValueStrategy);
  }
}(this, function(ApiClient, CompareOptions, DuplicateProductValueStrategy) {
  'use strict';




  /**
   * The DuplicateProductValueConfiguration model module.
   * @module model/DuplicateProductValueConfiguration
   * @version 2.0
   */

  /**
   * Constructs a new <code>DuplicateProductValueConfiguration</code>.
   * Describe how you
   * @alias module:model/DuplicateProductValueConfiguration
   * @class
   * @param strategy {module:model/DuplicateProductValueStrategy} 
   * @param compareOptions {module:model/CompareOptions} 
   */
  var exports = function(strategy, compareOptions) {
    var _this = this;

    _this['strategy'] = strategy;
    _this['compareOptions'] = compareOptions;
  };

  /**
   * Constructs a <code>DuplicateProductValueConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DuplicateProductValueConfiguration} obj Optional instance to populate.
   * @return {module:model/DuplicateProductValueConfiguration} The populated <code>DuplicateProductValueConfiguration</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('strategy')) {
        obj['strategy'] = DuplicateProductValueStrategy.constructFromObject(data['strategy']);
      }
      if (data.hasOwnProperty('compareOptions')) {
        obj['compareOptions'] = CompareOptions.constructFromObject(data['compareOptions']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/DuplicateProductValueStrategy} strategy
   */
  exports.prototype['strategy'] = undefined;
  /**
   * @member {module:model/CompareOptions} compareOptions
   */
  exports.prototype['compareOptions'] = undefined;



  return exports;
}));


