/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.FunctionalityRightInfo = factory(root.BeezUpApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FunctionalityRightInfo model module.
   * @module model/FunctionalityRightInfo
   * @version 2.0
   */

  /**
   * Constructs a new <code>FunctionalityRightInfo</code>.
   * Describe the rights for a functionality
   * @alias module:model/FunctionalityRightInfo
   * @class
   * @param functionalityCode {String} The functionality code
   */
  var exports = function(functionalityCode) {
    var _this = this;

    _this['functionalityCode'] = functionalityCode;


  };

  /**
   * Constructs a <code>FunctionalityRightInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FunctionalityRightInfo} obj Optional instance to populate.
   * @return {module:model/FunctionalityRightInfo} The populated <code>FunctionalityRightInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('functionalityCode')) {
        obj['functionalityCode'] = ApiClient.convertToType(data['functionalityCode'], 'String');
      }
      if (data.hasOwnProperty('maxValueInterger')) {
        obj['maxValueInterger'] = ApiClient.convertToType(data['maxValueInterger'], 'Number');
      }
      if (data.hasOwnProperty('unlimited')) {
        obj['unlimited'] = ApiClient.convertToType(data['unlimited'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * The functionality code
   * @member {String} functionalityCode
   */
  exports.prototype['functionalityCode'] = undefined;
  /**
   * The max value for this functionality code considering your rights
   * @member {Number} maxValueInterger
   */
  exports.prototype['maxValueInterger'] = undefined;
  /**
   * If you can use this functionality unlimitedly
   * @member {Boolean} unlimited
   */
  exports.prototype['unlimited'] = undefined;



  return exports;
}));


