/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.GeneralSettings = factory(root.BeezUpApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GeneralSettings model module.
   * @module model/GeneralSettings
   * @version 2.0
   */

  /**
   * Constructs a new <code>GeneralSettings</code>.
   * Represents the general settings of your channel catalog
   * @alias module:model/GeneralSettings
   * @class
   * @param acceptToPublishInfo {Boolean} If true then you authorize disclosure of my statistics generated from clicks and sales
   * @param useBid {Boolean} Activate bidding for this channel
   * @param noCategoryMapping {Boolean} Indicates that the channel authorize you to do not map your categories with their categories
   * @param doNotExportOutOfStockProducts {Boolean} Do not export \"out of stock\" products. Note: this option is not taken into account by the counter. 
   * @param activeBeezUPTracking {Boolean} Activate BeezUP tracking for my statistics (checked by default)
   */
  var exports = function(acceptToPublishInfo, useBid, noCategoryMapping, doNotExportOutOfStockProducts, activeBeezUPTracking) {
    var _this = this;

    _this['acceptToPublishInfo'] = acceptToPublishInfo;
    _this['useBid'] = useBid;
    _this['noCategoryMapping'] = noCategoryMapping;
    _this['doNotExportOutOfStockProducts'] = doNotExportOutOfStockProducts;
    _this['activeBeezUPTracking'] = activeBeezUPTracking;
  };

  /**
   * Constructs a <code>GeneralSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GeneralSettings} obj Optional instance to populate.
   * @return {module:model/GeneralSettings} The populated <code>GeneralSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('acceptToPublishInfo')) {
        obj['acceptToPublishInfo'] = ApiClient.convertToType(data['acceptToPublishInfo'], 'Boolean');
      }
      if (data.hasOwnProperty('useBid')) {
        obj['useBid'] = ApiClient.convertToType(data['useBid'], 'Boolean');
      }
      if (data.hasOwnProperty('noCategoryMapping')) {
        obj['noCategoryMapping'] = ApiClient.convertToType(data['noCategoryMapping'], 'Boolean');
      }
      if (data.hasOwnProperty('doNotExportOutOfStockProducts')) {
        obj['doNotExportOutOfStockProducts'] = ApiClient.convertToType(data['doNotExportOutOfStockProducts'], 'Boolean');
      }
      if (data.hasOwnProperty('activeBeezUPTracking')) {
        obj['activeBeezUPTracking'] = ApiClient.convertToType(data['activeBeezUPTracking'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * If true then you authorize disclosure of my statistics generated from clicks and sales
   * @member {Boolean} acceptToPublishInfo
   */
  exports.prototype['acceptToPublishInfo'] = undefined;
  /**
   * Activate bidding for this channel
   * @member {Boolean} useBid
   */
  exports.prototype['useBid'] = undefined;
  /**
   * Indicates that the channel authorize you to do not map your categories with their categories
   * @member {Boolean} noCategoryMapping
   */
  exports.prototype['noCategoryMapping'] = undefined;
  /**
   * Do not export \"out of stock\" products. Note: this option is not taken into account by the counter. 
   * @member {Boolean} doNotExportOutOfStockProducts
   */
  exports.prototype['doNotExportOutOfStockProducts'] = undefined;
  /**
   * Activate BeezUP tracking for my statistics (checked by default)
   * @member {Boolean} activeBeezUPTracking
   * @default true
   */
  exports.prototype['activeBeezUPTracking'] = true;



  return exports;
}));


