/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonUserErrorMessage', 'model/BeezUPCommonUserId'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonUserErrorMessage'), require('./BeezUPCommonUserId'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ImportationReporting = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonUserErrorMessage, root.BeezUpApi.BeezUPCommonUserId);
  }
}(this, function(ApiClient, BeezUPCommonUserErrorMessage, BeezUPCommonUserId) {
  'use strict';




  /**
   * The ImportationReporting model module.
   * @module model/ImportationReporting
   * @version 2.0
   */

  /**
   * Constructs a new <code>ImportationReporting</code>.
   * The catalog importation reporting
   * @alias module:model/ImportationReporting
   * @class
   * @param lastUpdateUtcDate {Date} Indicate the last update UTC date of the reporting.
   * @param beginUtcDate {Date} Indicate the begin UTC date of this importation.
   * @param steps {Object.<String, Boolean>} Indicate the steps that have been passed during the importation process
   */
  var exports = function(lastUpdateUtcDate, beginUtcDate, steps) {
    var _this = this;








    _this['lastUpdateUtcDate'] = lastUpdateUtcDate;

    _this['beginUtcDate'] = beginUtcDate;


    _this['steps'] = steps;
  };

  /**
   * Constructs a <code>ImportationReporting</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImportationReporting} obj Optional instance to populate.
   * @return {module:model/ImportationReporting} The populated <code>ImportationReporting</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('stepName')) {
        obj['stepName'] = ApiClient.convertToType(data['stepName'], 'String');
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = BeezUPCommonUserId.constructFromObject(data['userId']);
      }
      if (data.hasOwnProperty('success')) {
        obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
      }
      if (data.hasOwnProperty('totalProductCount')) {
        obj['totalProductCount'] = ApiClient.convertToType(data['totalProductCount'], 'Number');
      }
      if (data.hasOwnProperty('totalProductErrorCount')) {
        obj['totalProductErrorCount'] = ApiClient.convertToType(data['totalProductErrorCount'], 'Number');
      }
      if (data.hasOwnProperty('totalProductSuccessCount')) {
        obj['totalProductSuccessCount'] = ApiClient.convertToType(data['totalProductSuccessCount'], 'Number');
      }
      if (data.hasOwnProperty('errors')) {
        obj['errors'] = ApiClient.convertToType(data['errors'], [BeezUPCommonUserErrorMessage]);
      }
      if (data.hasOwnProperty('lastUpdateUtcDate')) {
        obj['lastUpdateUtcDate'] = ApiClient.convertToType(data['lastUpdateUtcDate'], 'Date');
      }
      if (data.hasOwnProperty('autoImported')) {
        obj['autoImported'] = ApiClient.convertToType(data['autoImported'], 'Boolean');
      }
      if (data.hasOwnProperty('beginUtcDate')) {
        obj['beginUtcDate'] = ApiClient.convertToType(data['beginUtcDate'], 'Date');
      }
      if (data.hasOwnProperty('endUtcDate')) {
        obj['endUtcDate'] = ApiClient.convertToType(data['endUtcDate'], 'Date');
      }
      if (data.hasOwnProperty('inputConfigurationUrl')) {
        obj['inputConfigurationUrl'] = ApiClient.convertToType(data['inputConfigurationUrl'], 'String');
      }
      if (data.hasOwnProperty('steps')) {
        obj['steps'] = ApiClient.convertToType(data['steps'], {'String': 'Boolean'});
      }
    }
    return obj;
  }

  /**
   * The last step name of the importation process
   * @member {String} stepName
   */
  exports.prototype['stepName'] = undefined;
  /**
   * @member {module:model/BeezUPCommonUserId} userId
   */
  exports.prototype['userId'] = undefined;
  /**
   * Indicate if the importation succeed or not.
   * @member {Boolean} success
   */
  exports.prototype['success'] = undefined;
  /**
   * Indicate the total product count detected in the catalog during the importation.
   * @member {Number} totalProductCount
   */
  exports.prototype['totalProductCount'] = undefined;
  /**
   * Indicate the total product count in error detected in the catalog during the importation.
   * @member {Number} totalProductErrorCount
   */
  exports.prototype['totalProductErrorCount'] = undefined;
  /**
   * Indicate the total product count in success in the catalog during the importation.
   * @member {Number} totalProductSuccessCount
   */
  exports.prototype['totalProductSuccessCount'] = undefined;
  /**
   * Indicate the error message list related to this importation.
   * @member {Array.<module:model/BeezUPCommonUserErrorMessage>} errors
   */
  exports.prototype['errors'] = undefined;
  /**
   * Indicate the last update UTC date of the reporting.
   * @member {Date} lastUpdateUtcDate
   */
  exports.prototype['lastUpdateUtcDate'] = undefined;
  /**
   * Indicate if this importation is an auto import or not.
   * @member {Boolean} autoImported
   */
  exports.prototype['autoImported'] = undefined;
  /**
   * Indicate the begin UTC date of this importation.
   * @member {Date} beginUtcDate
   */
  exports.prototype['beginUtcDate'] = undefined;
  /**
   * Indicate the end UTC date of this importation.
   * @member {Date} endUtcDate
   */
  exports.prototype['endUtcDate'] = undefined;
  /**
   * Indicate the input url of this importation.
   * @member {String} inputConfigurationUrl
   */
  exports.prototype['inputConfigurationUrl'] = undefined;
  /**
   * Indicate the steps that have been passed during the importation process
   * @member {Object.<String, Boolean>} steps
   */
  exports.prototype['steps'] = undefined;



  return exports;
}));


