/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonLOVLink3'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonLOVLink3'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.MarketplaceChannelCatalogLovLinks = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonLOVLink3);
  }
}(this, function(ApiClient, BeezUPCommonLOVLink3) {
  'use strict';




  /**
   * The MarketplaceChannelCatalogLovLinks model module.
   * @module model/MarketplaceChannelCatalogLovLinks
   * @version 2.0
   */

  /**
   * Constructs a new <code>MarketplaceChannelCatalogLovLinks</code>.
   * Indicates the List Of Values related to the marketplace
   * @alias module:model/MarketplaceChannelCatalogLovLinks
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>MarketplaceChannelCatalogLovLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MarketplaceChannelCatalogLovLinks} obj Optional instance to populate.
   * @return {module:model/MarketplaceChannelCatalogLovLinks} The populated <code>MarketplaceChannelCatalogLovLinks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('shippingMethodLOV')) {
        obj['shippingMethodLOV'] = BeezUPCommonLOVLink3.constructFromObject(data['shippingMethodLOV']);
      }
      if (data.hasOwnProperty('carrierCodeLOV')) {
        obj['carrierCodeLOV'] = BeezUPCommonLOVLink3.constructFromObject(data['carrierCodeLOV']);
      }
      if (data.hasOwnProperty('cancelationReasonCodeLOV')) {
        obj['cancelationReasonCodeLOV'] = BeezUPCommonLOVLink3.constructFromObject(data['cancelationReasonCodeLOV']);
      }
      if (data.hasOwnProperty('refundReasonCodeLOV')) {
        obj['refundReasonCodeLOV'] = BeezUPCommonLOVLink3.constructFromObject(data['refundReasonCodeLOV']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BeezUPCommonLOVLink3} shippingMethodLOV
   */
  exports.prototype['shippingMethodLOV'] = undefined;
  /**
   * @member {module:model/BeezUPCommonLOVLink3} carrierCodeLOV
   */
  exports.prototype['carrierCodeLOV'] = undefined;
  /**
   * @member {module:model/BeezUPCommonLOVLink3} cancelationReasonCodeLOV
   */
  exports.prototype['cancelationReasonCodeLOV'] = undefined;
  /**
   * @member {module:model/BeezUPCommonLOVLink3} refundReasonCodeLOV
   */
  exports.prototype['refundReasonCodeLOV'] = undefined;



  return exports;
}));


