/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.OfferFunctionality = factory(root.BeezUpApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OfferFunctionality model module.
   * @module model/OfferFunctionality
   * @version 2.0
   */

  /**
   * Constructs a new <code>OfferFunctionality</code>.
   * @alias module:model/OfferFunctionality
   * @class
   * @param functionalityCode {String} The functionality code
   * @param unlimited {Boolean} Is this feature is unlimited for this offer?
   */
  var exports = function(functionalityCode, unlimited) {
    var _this = this;

    _this['functionalityCode'] = functionalityCode;

    _this['unlimited'] = unlimited;

  };

  /**
   * Constructs a <code>OfferFunctionality</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OfferFunctionality} obj Optional instance to populate.
   * @return {module:model/OfferFunctionality} The populated <code>OfferFunctionality</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('functionalityCode')) {
        obj['functionalityCode'] = ApiClient.convertToType(data['functionalityCode'], 'String');
      }
      if (data.hasOwnProperty('maxValueInteger')) {
        obj['maxValueInteger'] = ApiClient.convertToType(data['maxValueInteger'], 'Number');
      }
      if (data.hasOwnProperty('unlimited')) {
        obj['unlimited'] = ApiClient.convertToType(data['unlimited'], 'Boolean');
      }
      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], 'String');
      }
    }
    return obj;
  }

  /**
   * The functionality code
   * @member {String} functionalityCode
   */
  exports.prototype['functionalityCode'] = undefined;
  /**
   * The max value in integer for this feature in this offer
   * @member {Number} maxValueInteger
   */
  exports.prototype['maxValueInteger'] = undefined;
  /**
   * Is this feature is unlimited for this offer?
   * @member {Boolean} unlimited
   */
  exports.prototype['unlimited'] = undefined;
  /**
   * A description text of this feature
   * @member {String} text
   */
  exports.prototype['text'] = undefined;



  return exports;
}));


