/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonInfoSummaries', 'model/OfferContent', 'model/OfferLinks'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonInfoSummaries'), require('./OfferContent'), require('./OfferLinks'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.Offer = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonInfoSummaries, root.BeezUpApi.OfferContent, root.BeezUpApi.OfferLinks);
  }
}(this, function(ApiClient, BeezUPCommonInfoSummaries, OfferContent, OfferLinks) {
  'use strict';




  /**
   * The Offer model module.
   * @module model/Offer
   * @version 2.0
   */

  /**
   * Constructs a new <code>Offer</code>.
   * @alias module:model/Offer
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Offer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Offer} obj Optional instance to populate.
   * @return {module:model/Offer} The populated <code>Offer</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('content')) {
        obj['content'] = OfferContent.constructFromObject(data['content']);
      }
      if (data.hasOwnProperty('info')) {
        obj['info'] = BeezUPCommonInfoSummaries.constructFromObject(data['info']);
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = OfferLinks.constructFromObject(data['links']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/OfferContent} content
   */
  exports.prototype['content'] = undefined;
  /**
   * @member {module:model/BeezUPCommonInfoSummaries} info
   */
  exports.prototype['info'] = undefined;
  /**
   * @member {module:model/OfferLinks} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


