/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonPaginationResult', 'model/Order', 'model/OrderListFullLinks'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonPaginationResult'), require('./Order'), require('./OrderListFullLinks'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.OrderListFull = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonPaginationResult, root.BeezUpApi.Order, root.BeezUpApi.OrderListFullLinks);
  }
}(this, function(ApiClient, BeezUPCommonPaginationResult, Order, OrderListFullLinks) {
  'use strict';




  /**
   * The OrderListFull model module.
   * @module model/OrderListFull
   * @version 2.0
   */

  /**
   * Constructs a new <code>OrderListFull</code>.
   * The order list with all information we have from the orders and its items.\\ The paginationResult properties can be null if the list is empty.  
   * @alias module:model/OrderListFull
   * @class
   * @param orders {Array.<module:model/Order>} 
   * @param links {module:model/OrderListFullLinks} 
   */
  var exports = function(orders, links) {
    var _this = this;


    _this['orders'] = orders;
    _this['links'] = links;
  };

  /**
   * Constructs a <code>OrderListFull</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderListFull} obj Optional instance to populate.
   * @return {module:model/OrderListFull} The populated <code>OrderListFull</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('paginationResult')) {
        obj['paginationResult'] = BeezUPCommonPaginationResult.constructFromObject(data['paginationResult']);
      }
      if (data.hasOwnProperty('orders')) {
        obj['orders'] = ApiClient.convertToType(data['orders'], [Order]);
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = OrderListFullLinks.constructFromObject(data['links']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BeezUPCommonPaginationResult} paginationResult
   */
  exports.prototype['paginationResult'] = undefined;
  /**
   * @member {Array.<module:model/Order>} orders
   */
  exports.prototype['orders'] = undefined;
  /**
   * @member {module:model/OrderListFullLinks} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


