/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountId', 'model/BeezUPCommonCurrencyCode', 'model/BeezUPCommonHttpUrl', 'model/BeezUPCommonMarketplaceBusinessCode', 'model/BeezUPCommonMarketplaceTechnicalCode', 'model/BeezUPOrderId', 'model/BeezUPOrderStatus', 'model/Etag', 'model/MarketplaceOrderId', 'model/MarketplaceOrderStatus', 'model/OrderBuyerName', 'model/OrderHeaderLinks', 'model/OrderMerchantECommerceSoftwareName', 'model/OrderMerchantECommerceSoftwareVersion', 'model/OrderMerchantOrderId', 'model/Processing'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccountId'), require('./BeezUPCommonCurrencyCode'), require('./BeezUPCommonHttpUrl'), require('./BeezUPCommonMarketplaceBusinessCode'), require('./BeezUPCommonMarketplaceTechnicalCode'), require('./BeezUPOrderId'), require('./BeezUPOrderStatus'), require('./Etag'), require('./MarketplaceOrderId'), require('./MarketplaceOrderStatus'), require('./OrderBuyerName'), require('./OrderHeaderLinks'), require('./OrderMerchantECommerceSoftwareName'), require('./OrderMerchantECommerceSoftwareVersion'), require('./OrderMerchantOrderId'), require('./Processing'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.OrderHeader = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.AccountId, root.BeezUpApi.BeezUPCommonCurrencyCode, root.BeezUpApi.BeezUPCommonHttpUrl, root.BeezUpApi.BeezUPCommonMarketplaceBusinessCode, root.BeezUpApi.BeezUPCommonMarketplaceTechnicalCode, root.BeezUpApi.BeezUPOrderId, root.BeezUpApi.BeezUPOrderStatus, root.BeezUpApi.Etag, root.BeezUpApi.MarketplaceOrderId, root.BeezUpApi.MarketplaceOrderStatus, root.BeezUpApi.OrderBuyerName, root.BeezUpApi.OrderHeaderLinks, root.BeezUpApi.OrderMerchantECommerceSoftwareName, root.BeezUpApi.OrderMerchantECommerceSoftwareVersion, root.BeezUpApi.OrderMerchantOrderId, root.BeezUpApi.Processing);
  }
}(this, function(ApiClient, AccountId, BeezUPCommonCurrencyCode, BeezUPCommonHttpUrl, BeezUPCommonMarketplaceBusinessCode, BeezUPCommonMarketplaceTechnicalCode, BeezUPOrderId, BeezUPOrderStatus, Etag, MarketplaceOrderId, MarketplaceOrderStatus, OrderBuyerName, OrderHeaderLinks, OrderMerchantECommerceSoftwareName, OrderMerchantECommerceSoftwareVersion, OrderMerchantOrderId, Processing) {
  'use strict';




  /**
   * The OrderHeader model module.
   * @module model/OrderHeader
   * @version 2.0
   */

  /**
   * Constructs a new <code>OrderHeader</code>.
   * Describe the basic information related to an order. All properties with the prefix order_ are translated in the list of values /user/lov/OrderMetaInfoOrderDetails
   * @alias module:model/OrderHeader
   * @class
   * @param marketplaceTechnicalCode {module:model/BeezUPCommonMarketplaceTechnicalCode} 
   * @param accountId {module:model/AccountId} 
   * @param beezUPOrderId {module:model/BeezUPOrderId} 
   * @param marketplaceBusinessCode {module:model/BeezUPCommonMarketplaceBusinessCode} 
   * @param orderMarketplaceOrderId {module:model/MarketplaceOrderId} 
   * @param orderStatusBeezUPOrderStatus {module:model/BeezUPOrderStatus} 
   * @param orderPurchaseUtcDate {Date} The purchase date of this order
   * @param orderLastModificationUtcDate {Date} The last modification UTC date done by BeezUP of this order
   * @param orderMarketplaceLastModificationUtcDate {Date} The last modification UTC date done by the marketplace on this order
   * @param processing {module:model/Processing} 
   * @param etag {module:model/Etag} 
   * @param links {module:model/OrderHeaderLinks} 
   */
  var exports = function(marketplaceTechnicalCode, accountId, beezUPOrderId, marketplaceBusinessCode, orderMarketplaceOrderId, orderStatusBeezUPOrderStatus, orderPurchaseUtcDate, orderLastModificationUtcDate, orderMarketplaceLastModificationUtcDate, processing, etag, links) {
    var _this = this;

    _this['marketplaceTechnicalCode'] = marketplaceTechnicalCode;
    _this['accountId'] = accountId;
    _this['beezUPOrderId'] = beezUPOrderId;

    _this['marketplaceBusinessCode'] = marketplaceBusinessCode;
    _this['order_MarketplaceOrderId'] = orderMarketplaceOrderId;
    _this['order_Status_BeezUPOrderStatus'] = orderStatusBeezUPOrderStatus;




    _this['order_PurchaseUtcDate'] = orderPurchaseUtcDate;
    _this['order_LastModificationUtcDate'] = orderLastModificationUtcDate;
    _this['order_MarketplaceLastModificationUtcDate'] = orderMarketplaceLastModificationUtcDate;



    _this['processing'] = processing;
    _this['etag'] = etag;
    _this['links'] = links;
  };

  /**
   * Constructs a <code>OrderHeader</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderHeader} obj Optional instance to populate.
   * @return {module:model/OrderHeader} The populated <code>OrderHeader</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('marketplaceTechnicalCode')) {
        obj['marketplaceTechnicalCode'] = BeezUPCommonMarketplaceTechnicalCode.constructFromObject(data['marketplaceTechnicalCode']);
      }
      if (data.hasOwnProperty('accountId')) {
        obj['accountId'] = AccountId.constructFromObject(data['accountId']);
      }
      if (data.hasOwnProperty('beezUPOrderId')) {
        obj['beezUPOrderId'] = BeezUPOrderId.constructFromObject(data['beezUPOrderId']);
      }
      if (data.hasOwnProperty('beezUPOrderUrl')) {
        obj['beezUPOrderUrl'] = BeezUPCommonHttpUrl.constructFromObject(data['beezUPOrderUrl']);
      }
      if (data.hasOwnProperty('marketplaceBusinessCode')) {
        obj['marketplaceBusinessCode'] = BeezUPCommonMarketplaceBusinessCode.constructFromObject(data['marketplaceBusinessCode']);
      }
      if (data.hasOwnProperty('order_MarketplaceOrderId')) {
        obj['order_MarketplaceOrderId'] = MarketplaceOrderId.constructFromObject(data['order_MarketplaceOrderId']);
      }
      if (data.hasOwnProperty('order_Status_BeezUPOrderStatus')) {
        obj['order_Status_BeezUPOrderStatus'] = BeezUPOrderStatus.constructFromObject(data['order_Status_BeezUPOrderStatus']);
      }
      if (data.hasOwnProperty('order_Status_MarketplaceOrderStatus')) {
        obj['order_Status_MarketplaceOrderStatus'] = MarketplaceOrderStatus.constructFromObject(data['order_Status_MarketplaceOrderStatus']);
      }
      if (data.hasOwnProperty('order_MerchantOrderId')) {
        obj['order_MerchantOrderId'] = OrderMerchantOrderId.constructFromObject(data['order_MerchantOrderId']);
      }
      if (data.hasOwnProperty('order_MerchantECommerceSoftwareName')) {
        obj['order_MerchantECommerceSoftwareName'] = OrderMerchantECommerceSoftwareName.constructFromObject(data['order_MerchantECommerceSoftwareName']);
      }
      if (data.hasOwnProperty('order_MerchantECommerceSoftwareVersion')) {
        obj['order_MerchantECommerceSoftwareVersion'] = OrderMerchantECommerceSoftwareVersion.constructFromObject(data['order_MerchantECommerceSoftwareVersion']);
      }
      if (data.hasOwnProperty('order_PurchaseUtcDate')) {
        obj['order_PurchaseUtcDate'] = ApiClient.convertToType(data['order_PurchaseUtcDate'], 'Date');
      }
      if (data.hasOwnProperty('order_LastModificationUtcDate')) {
        obj['order_LastModificationUtcDate'] = ApiClient.convertToType(data['order_LastModificationUtcDate'], 'Date');
      }
      if (data.hasOwnProperty('order_MarketplaceLastModificationUtcDate')) {
        obj['order_MarketplaceLastModificationUtcDate'] = ApiClient.convertToType(data['order_MarketplaceLastModificationUtcDate'], 'Date');
      }
      if (data.hasOwnProperty('order_Buyer_Name')) {
        obj['order_Buyer_Name'] = OrderBuyerName.constructFromObject(data['order_Buyer_Name']);
      }
      if (data.hasOwnProperty('order_TotalPrice')) {
        obj['order_TotalPrice'] = ApiClient.convertToType(data['order_TotalPrice'], 'Number');
      }
      if (data.hasOwnProperty('order_CurrencyCode')) {
        obj['order_CurrencyCode'] = BeezUPCommonCurrencyCode.constructFromObject(data['order_CurrencyCode']);
      }
      if (data.hasOwnProperty('processing')) {
        obj['processing'] = Processing.constructFromObject(data['processing']);
      }
      if (data.hasOwnProperty('etag')) {
        obj['etag'] = Etag.constructFromObject(data['etag']);
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = OrderHeaderLinks.constructFromObject(data['links']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BeezUPCommonMarketplaceTechnicalCode} marketplaceTechnicalCode
   */
  exports.prototype['marketplaceTechnicalCode'] = undefined;
  /**
   * @member {module:model/AccountId} accountId
   */
  exports.prototype['accountId'] = undefined;
  /**
   * @member {module:model/BeezUPOrderId} beezUPOrderId
   */
  exports.prototype['beezUPOrderId'] = undefined;
  /**
   * @member {module:model/BeezUPCommonHttpUrl} beezUPOrderUrl
   */
  exports.prototype['beezUPOrderUrl'] = undefined;
  /**
   * @member {module:model/BeezUPCommonMarketplaceBusinessCode} marketplaceBusinessCode
   */
  exports.prototype['marketplaceBusinessCode'] = undefined;
  /**
   * @member {module:model/MarketplaceOrderId} order_MarketplaceOrderId
   */
  exports.prototype['order_MarketplaceOrderId'] = undefined;
  /**
   * @member {module:model/BeezUPOrderStatus} order_Status_BeezUPOrderStatus
   */
  exports.prototype['order_Status_BeezUPOrderStatus'] = undefined;
  /**
   * @member {module:model/MarketplaceOrderStatus} order_Status_MarketplaceOrderStatus
   */
  exports.prototype['order_Status_MarketplaceOrderStatus'] = undefined;
  /**
   * @member {module:model/OrderMerchantOrderId} order_MerchantOrderId
   */
  exports.prototype['order_MerchantOrderId'] = undefined;
  /**
   * @member {module:model/OrderMerchantECommerceSoftwareName} order_MerchantECommerceSoftwareName
   */
  exports.prototype['order_MerchantECommerceSoftwareName'] = undefined;
  /**
   * @member {module:model/OrderMerchantECommerceSoftwareVersion} order_MerchantECommerceSoftwareVersion
   */
  exports.prototype['order_MerchantECommerceSoftwareVersion'] = undefined;
  /**
   * The purchase date of this order
   * @member {Date} order_PurchaseUtcDate
   */
  exports.prototype['order_PurchaseUtcDate'] = undefined;
  /**
   * The last modification UTC date done by BeezUP of this order
   * @member {Date} order_LastModificationUtcDate
   */
  exports.prototype['order_LastModificationUtcDate'] = undefined;
  /**
   * The last modification UTC date done by the marketplace on this order
   * @member {Date} order_MarketplaceLastModificationUtcDate
   */
  exports.prototype['order_MarketplaceLastModificationUtcDate'] = undefined;
  /**
   * @member {module:model/OrderBuyerName} order_Buyer_Name
   */
  exports.prototype['order_Buyer_Name'] = undefined;
  /**
   * The total price of this order (corresponding to the amount paid by the customer)
   * @member {Number} order_TotalPrice
   */
  exports.prototype['order_TotalPrice'] = undefined;
  /**
   * @member {module:model/BeezUPCommonCurrencyCode} order_CurrencyCode
   */
  exports.prototype['order_CurrencyCode'] = undefined;
  /**
   * @member {module:model/Processing} processing
   */
  exports.prototype['processing'] = undefined;
  /**
   * @member {module:model/Etag} etag
   */
  exports.prototype['etag'] = undefined;
  /**
   * @member {module:model/OrderHeaderLinks} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


