/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrderIndexLinks', 'model/OrderIndexLovLinks'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OrderIndexLinks'), require('./OrderIndexLovLinks'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.OrderIndex = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.OrderIndexLinks, root.BeezUpApi.OrderIndexLovLinks);
  }
}(this, function(ApiClient, OrderIndexLinks, OrderIndexLovLinks) {
  'use strict';




  /**
   * The OrderIndex model module.
   * @module model/OrderIndex
   * @version 2.0
   */

  /**
   * Constructs a new <code>OrderIndex</code>.
   * @alias module:model/OrderIndex
   * @class
   * @param links {module:model/OrderIndexLinks} 
   * @param lovLinks {module:model/OrderIndexLovLinks} 
   */
  var exports = function(links, lovLinks) {
    var _this = this;

    _this['links'] = links;
    _this['lovLinks'] = lovLinks;
  };

  /**
   * Constructs a <code>OrderIndex</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderIndex} obj Optional instance to populate.
   * @return {module:model/OrderIndex} The populated <code>OrderIndex</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('links')) {
        obj['links'] = OrderIndexLinks.constructFromObject(data['links']);
      }
      if (data.hasOwnProperty('lovLinks')) {
        obj['lovLinks'] = OrderIndexLovLinks.constructFromObject(data['lovLinks']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/OrderIndexLinks} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {module:model/OrderIndexLovLinks} lovLinks
   */
  exports.prototype['lovLinks'] = undefined;



  return exports;
}));


