/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProductOverrideWithCatalogValue'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ProductOverrideWithCatalogValue'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ProductOverridesWithCatalogValues = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.ProductOverrideWithCatalogValue);
  }
}(this, function(ApiClient, ProductOverrideWithCatalogValue) {
  'use strict';




  /**
   * The ProductOverridesWithCatalogValues model module.
   * @module model/ProductOverridesWithCatalogValues
   * @version 2.0
   */

  /**
   * Constructs a new <code>ProductOverridesWithCatalogValues</code>.
   * The key is the channel column identifier
   * @alias module:model/ProductOverridesWithCatalogValues
   * @class
   * @extends Object
   */
  var exports = function() {
    var _this = this;

    return _this;
  };

  /**
   * Constructs a <code>ProductOverridesWithCatalogValues</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductOverridesWithCatalogValues} obj Optional instance to populate.
   * @return {module:model/ProductOverridesWithCatalogValues} The populated <code>ProductOverridesWithCatalogValues</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'ProductOverrideWithCatalogValue');

    }
    return obj;
  }




  return exports;
}));


