/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GravatarProfilePictureUrl', 'model/InitialsProfilePictureUrl', 'model/ProfilePictureInfo', 'model/ProfilePictureSelected', 'model/ProfilePictureUrl'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GravatarProfilePictureUrl'), require('./InitialsProfilePictureUrl'), require('./ProfilePictureInfo'), require('./ProfilePictureSelected'), require('./ProfilePictureUrl'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ProfilePictureInfoWithDefault = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.GravatarProfilePictureUrl, root.BeezUpApi.InitialsProfilePictureUrl, root.BeezUpApi.ProfilePictureInfo, root.BeezUpApi.ProfilePictureSelected, root.BeezUpApi.ProfilePictureUrl);
  }
}(this, function(ApiClient, GravatarProfilePictureUrl, InitialsProfilePictureUrl, ProfilePictureInfo, ProfilePictureSelected, ProfilePictureUrl) {
  'use strict';




  /**
   * The ProfilePictureInfoWithDefault model module.
   * @module model/ProfilePictureInfoWithDefault
   * @version 2.0
   */

  /**
   * Constructs a new <code>ProfilePictureInfoWithDefault</code>.
   * @alias module:model/ProfilePictureInfoWithDefault
   * @class
   * @implements module:model/ProfilePictureInfo
   * @param profilePictureSelected {module:model/ProfilePictureSelected} 
   * @param initialsProfilePictureUrl {module:model/InitialsProfilePictureUrl} 
   * @param gravatarProfilePictureUrl {module:model/GravatarProfilePictureUrl} 
   */
  var exports = function(profilePictureSelected, initialsProfilePictureUrl, gravatarProfilePictureUrl) {
    var _this = this;

    ProfilePictureInfo.call(_this, profilePictureSelected);
    _this['initialsProfilePictureUrl'] = initialsProfilePictureUrl;
    _this['gravatarProfilePictureUrl'] = gravatarProfilePictureUrl;
  };

  /**
   * Constructs a <code>ProfilePictureInfoWithDefault</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProfilePictureInfoWithDefault} obj Optional instance to populate.
   * @return {module:model/ProfilePictureInfoWithDefault} The populated <code>ProfilePictureInfoWithDefault</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      ProfilePictureInfo.constructFromObject(data, obj);
      if (data.hasOwnProperty('initialsProfilePictureUrl')) {
        obj['initialsProfilePictureUrl'] = InitialsProfilePictureUrl.constructFromObject(data['initialsProfilePictureUrl']);
      }
      if (data.hasOwnProperty('gravatarProfilePictureUrl')) {
        obj['gravatarProfilePictureUrl'] = GravatarProfilePictureUrl.constructFromObject(data['gravatarProfilePictureUrl']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InitialsProfilePictureUrl} initialsProfilePictureUrl
   */
  exports.prototype['initialsProfilePictureUrl'] = undefined;
  /**
   * @member {module:model/GravatarProfilePictureUrl} gravatarProfilePictureUrl
   */
  exports.prototype['gravatarProfilePictureUrl'] = undefined;

  // Implement ProfilePictureInfo interface:
  /**
   * @member {module:model/ProfilePictureUrl} profilePictureUrl
   */
exports.prototype['profilePictureUrl'] = undefined;

  /**
   * @member {module:model/ProfilePictureSelected} profilePictureSelected
   */
exports.prototype['profilePictureSelected'] = undefined;



  return exports;
}));


