/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonCurrencyCode', 'model/BeezUPCommonPaginationResult', 'model/ReportByChannel', 'model/ReportByChannelResponseLinks'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonCurrencyCode'), require('./BeezUPCommonPaginationResult'), require('./ReportByChannel'), require('./ReportByChannelResponseLinks'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ReportByChannelResponse = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonCurrencyCode, root.BeezUpApi.BeezUPCommonPaginationResult, root.BeezUpApi.ReportByChannel, root.BeezUpApi.ReportByChannelResponseLinks);
  }
}(this, function(ApiClient, BeezUPCommonCurrencyCode, BeezUPCommonPaginationResult, ReportByChannel, ReportByChannelResponseLinks) {
  'use strict';




  /**
   * The ReportByChannelResponse model module.
   * @module model/ReportByChannelResponse
   * @version 2.0
   */

  /**
   * Constructs a new <code>ReportByChannelResponse</code>.
   * @alias module:model/ReportByChannelResponse
   * @class
   * @param paginationResult {module:model/BeezUPCommonPaginationResult} 
   * @param currencyCode {module:model/BeezUPCommonCurrencyCode} 
   * @param channels {Array.<module:model/ReportByChannel>} 
   * @param links {module:model/ReportByChannelResponseLinks} 
   */
  var exports = function(paginationResult, currencyCode, channels, links) {
    var _this = this;

    _this['paginationResult'] = paginationResult;
    _this['currencyCode'] = currencyCode;
    _this['channels'] = channels;
    _this['links'] = links;
  };

  /**
   * Constructs a <code>ReportByChannelResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReportByChannelResponse} obj Optional instance to populate.
   * @return {module:model/ReportByChannelResponse} The populated <code>ReportByChannelResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('paginationResult')) {
        obj['paginationResult'] = BeezUPCommonPaginationResult.constructFromObject(data['paginationResult']);
      }
      if (data.hasOwnProperty('currencyCode')) {
        obj['currencyCode'] = BeezUPCommonCurrencyCode.constructFromObject(data['currencyCode']);
      }
      if (data.hasOwnProperty('channels')) {
        obj['channels'] = ApiClient.convertToType(data['channels'], [ReportByChannel]);
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = ReportByChannelResponseLinks.constructFromObject(data['links']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BeezUPCommonPaginationResult} paginationResult
   */
  exports.prototype['paginationResult'] = undefined;
  /**
   * @member {module:model/BeezUPCommonCurrencyCode} currencyCode
   */
  exports.prototype['currencyCode'] = undefined;
  /**
   * @member {Array.<module:model/ReportByChannel>} channels
   */
  exports.prototype['channels'] = undefined;
  /**
   * @member {module:model/ReportByChannelResponseLinks} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


