/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LinksOptimiseByChannelLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LinksOptimiseByChannelLink'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ReportByChannelLinks = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.LinksOptimiseByChannelLink);
  }
}(this, function(ApiClient, LinksOptimiseByChannelLink) {
  'use strict';




  /**
   * The ReportByChannelLinks model module.
   * @module model/ReportByChannelLinks
   * @version 2.0
   */

  /**
   * Constructs a new <code>ReportByChannelLinks</code>.
   * @alias module:model/ReportByChannelLinks
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ReportByChannelLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReportByChannelLinks} obj Optional instance to populate.
   * @return {module:model/ReportByChannelLinks} The populated <code>ReportByChannelLinks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('enableProducts')) {
        obj['enableProducts'] = LinksOptimiseByChannelLink.constructFromObject(data['enableProducts']);
      }
      if (data.hasOwnProperty('disableProducts')) {
        obj['disableProducts'] = LinksOptimiseByChannelLink.constructFromObject(data['disableProducts']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/LinksOptimiseByChannelLink} enableProducts
   */
  exports.prototype['enableProducts'] = undefined;
  /**
   * @member {module:model/LinksOptimiseByChannelLink} disableProducts
   */
  exports.prototype['disableProducts'] = undefined;



  return exports;
}));


