/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BeezUPCommonChannelId', 'model/ProductFilters', 'model/ProductStateFilter', 'model/ReportAdvancedFilters', 'model/ReportCategoryFilter', 'model/ReportFilterCommonParameters', 'model/ReportIndicatorFilter', 'model/ReportType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BeezUPCommonChannelId'), require('./ProductFilters'), require('./ProductStateFilter'), require('./ReportAdvancedFilters'), require('./ReportCategoryFilter'), require('./ReportFilterCommonParameters'), require('./ReportIndicatorFilter'), require('./ReportType'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ReportFilterParameters = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.BeezUPCommonChannelId, root.BeezUpApi.ProductFilters, root.BeezUpApi.ProductStateFilter, root.BeezUpApi.ReportAdvancedFilters, root.BeezUpApi.ReportCategoryFilter, root.BeezUpApi.ReportFilterCommonParameters, root.BeezUpApi.ReportIndicatorFilter, root.BeezUpApi.ReportType);
  }
}(this, function(ApiClient, BeezUPCommonChannelId, ProductFilters, ProductStateFilter, ReportAdvancedFilters, ReportCategoryFilter, ReportFilterCommonParameters, ReportIndicatorFilter, ReportType) {
  'use strict';




  /**
   * The ReportFilterParameters model module.
   * @module model/ReportFilterParameters
   * @version 2.0
   */

  /**
   * Constructs a new <code>ReportFilterParameters</code>.
   * @alias module:model/ReportFilterParameters
   * @class
   * @implements module:model/ReportFilterCommonParameters
   * @param beginPeriodUtcDate {Date} The begin date period you want to get the report
   * @param endPeriodUtcDate {Date} The end date period you want to get the report.
   * @param advancedFilters {module:model/ReportAdvancedFilters} 
   * @param reportType {module:model/ReportType} 
   */
  var exports = function(beginPeriodUtcDate, endPeriodUtcDate, advancedFilters, reportType) {
    var _this = this;

    ReportFilterCommonParameters.call(_this, beginPeriodUtcDate, endPeriodUtcDate, advancedFilters);
    _this['reportType'] = reportType;


  };

  /**
   * Constructs a <code>ReportFilterParameters</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReportFilterParameters} obj Optional instance to populate.
   * @return {module:model/ReportFilterParameters} The populated <code>ReportFilterParameters</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      ReportFilterCommonParameters.constructFromObject(data, obj);
      if (data.hasOwnProperty('reportType')) {
        obj['reportType'] = ReportType.constructFromObject(data['reportType']);
      }
      if (data.hasOwnProperty('productState')) {
        obj['productState'] = ProductStateFilter.constructFromObject(data['productState']);
      }
      if (data.hasOwnProperty('productFilters')) {
        obj['productFilters'] = ProductFilters.constructFromObject(data['productFilters']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ReportType} reportType
   */
  exports.prototype['reportType'] = undefined;
  /**
   * @member {module:model/ProductStateFilter} productState
   */
  exports.prototype['productState'] = undefined;
  /**
   * @member {module:model/ProductFilters} productFilters
   */
  exports.prototype['productFilters'] = undefined;

  // Implement ReportFilterCommonParameters interface:
  /**
   * @member {module:model/BeezUPCommonChannelId} channelId
   */
exports.prototype['channelId'] = undefined;

  /**
   * The begin date period you want to get the report
   * @member {Date} beginPeriodUtcDate
   */
exports.prototype['beginPeriodUtcDate'] = undefined;

  /**
   * The end date period you want to get the report.
   * @member {Date} endPeriodUtcDate
   */
exports.prototype['endPeriodUtcDate'] = undefined;

  /**
   * @member {module:model/ReportCategoryFilter} categoryFilter
   */
exports.prototype['categoryFilter'] = undefined;

  /**
   * @member {Array.<module:model/ReportIndicatorFilter>} indicatorFilters
   */
exports.prototype['indicatorFilters'] = undefined;

  /**
   * @member {module:model/ReportAdvancedFilters} advancedFilters
   */
exports.prototype['advancedFilters'] = undefined;



  return exports;
}));


