/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OptimisationActionName', 'model/RuleLastExecutionStatus', 'model/RuleLinks'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OptimisationActionName'), require('./RuleLastExecutionStatus'), require('./RuleLinks'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.Rule = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.OptimisationActionName, root.BeezUpApi.RuleLastExecutionStatus, root.BeezUpApi.RuleLinks);
  }
}(this, function(ApiClient, OptimisationActionName, RuleLastExecutionStatus, RuleLinks) {
  'use strict';




  /**
   * The Rule model module.
   * @module model/Rule
   * @version 2.0
   */

  /**
   * Constructs a new <code>Rule</code>.
   * @alias module:model/Rule
   * @class
   * @param ruleId {String} The identifier of the rule
   * @param ruleName {String} The name of the rule
   * @param actionName {module:model/OptimisationActionName} 
   * @param reportFilterId {String} Report filter identifier linked to the rule
   * @param position {Number} Rule execution position
   * @param enabled {Boolean} Is the rule enabled
   * @param links {module:model/RuleLinks} 
   */
  var exports = function(ruleId, ruleName, actionName, reportFilterId, position, enabled, links) {
    var _this = this;

    _this['ruleId'] = ruleId;
    _this['ruleName'] = ruleName;


    _this['actionName'] = actionName;
    _this['reportFilterId'] = reportFilterId;
    _this['position'] = position;
    _this['enabled'] = enabled;


    _this['links'] = links;
  };

  /**
   * Constructs a <code>Rule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Rule} obj Optional instance to populate.
   * @return {module:model/Rule} The populated <code>Rule</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ruleId')) {
        obj['ruleId'] = ApiClient.convertToType(data['ruleId'], 'String');
      }
      if (data.hasOwnProperty('ruleName')) {
        obj['ruleName'] = ApiClient.convertToType(data['ruleName'], 'String');
      }
      if (data.hasOwnProperty('lastExecutionStatus')) {
        obj['lastExecutionStatus'] = RuleLastExecutionStatus.constructFromObject(data['lastExecutionStatus']);
      }
      if (data.hasOwnProperty('lastExecutionUtcDate')) {
        obj['lastExecutionUtcDate'] = ApiClient.convertToType(data['lastExecutionUtcDate'], 'Date');
      }
      if (data.hasOwnProperty('actionName')) {
        obj['actionName'] = OptimisationActionName.constructFromObject(data['actionName']);
      }
      if (data.hasOwnProperty('reportFilterId')) {
        obj['reportFilterId'] = ApiClient.convertToType(data['reportFilterId'], 'String');
      }
      if (data.hasOwnProperty('position')) {
        obj['position'] = ApiClient.convertToType(data['position'], 'Number');
      }
      if (data.hasOwnProperty('enabled')) {
        obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
      }
      if (data.hasOwnProperty('validityStartUtcDate')) {
        obj['validityStartUtcDate'] = ApiClient.convertToType(data['validityStartUtcDate'], 'Date');
      }
      if (data.hasOwnProperty('validityEndUtcDate')) {
        obj['validityEndUtcDate'] = ApiClient.convertToType(data['validityEndUtcDate'], 'Date');
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = RuleLinks.constructFromObject(data['links']);
      }
    }
    return obj;
  }

  /**
   * The identifier of the rule
   * @member {String} ruleId
   */
  exports.prototype['ruleId'] = undefined;
  /**
   * The name of the rule
   * @member {String} ruleName
   */
  exports.prototype['ruleName'] = undefined;
  /**
   * @member {module:model/RuleLastExecutionStatus} lastExecutionStatus
   */
  exports.prototype['lastExecutionStatus'] = undefined;
  /**
   * The utc date of the last execution
   * @member {Date} lastExecutionUtcDate
   */
  exports.prototype['lastExecutionUtcDate'] = undefined;
  /**
   * @member {module:model/OptimisationActionName} actionName
   */
  exports.prototype['actionName'] = undefined;
  /**
   * Report filter identifier linked to the rule
   * @member {String} reportFilterId
   */
  exports.prototype['reportFilterId'] = undefined;
  /**
   * Rule execution position
   * @member {Number} position
   */
  exports.prototype['position'] = undefined;
  /**
   * Is the rule enabled
   * @member {Boolean} enabled
   */
  exports.prototype['enabled'] = undefined;
  /**
   * Rule validity start utc date
   * @member {Date} validityStartUtcDate
   */
  exports.prototype['validityStartUtcDate'] = undefined;
  /**
   * Rule validity end utc date
   * @member {Date} validityEndUtcDate
   */
  exports.prototype['validityEndUtcDate'] = undefined;
  /**
   * @member {module:model/RuleLinks} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


