/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ReportFilterParameters'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ReportFilterParameters'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.SaveReportFilterRequest = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.ReportFilterParameters);
  }
}(this, function(ApiClient, ReportFilterParameters) {
  'use strict';




  /**
   * The SaveReportFilterRequest model module.
   * @module model/SaveReportFilterRequest
   * @version 2.0
   */

  /**
   * Constructs a new <code>SaveReportFilterRequest</code>.
   * @alias module:model/SaveReportFilterRequest
   * @class
   * @param reportFilterName {String} Report filter name
   * @param parameters {module:model/ReportFilterParameters} 
   */
  var exports = function(reportFilterName, parameters) {
    var _this = this;

    _this['reportFilterName'] = reportFilterName;
    _this['parameters'] = parameters;
  };

  /**
   * Constructs a <code>SaveReportFilterRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SaveReportFilterRequest} obj Optional instance to populate.
   * @return {module:model/SaveReportFilterRequest} The populated <code>SaveReportFilterRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('reportFilterName')) {
        obj['reportFilterName'] = ApiClient.convertToType(data['reportFilterName'], 'String');
      }
      if (data.hasOwnProperty('parameters')) {
        obj['parameters'] = ReportFilterParameters.constructFromObject(data['parameters']);
      }
    }
    return obj;
  }

  /**
   * Report filter name
   * @member {String} reportFilterName
   */
  exports.prototype['reportFilterName'] = undefined;
  /**
   * @member {module:model/ReportFilterParameters} parameters
   */
  exports.prototype['parameters'] = undefined;



  return exports;
}));


