/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.ScheduleAutoImportRequest = factory(root.BeezUpApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ScheduleAutoImportRequest model module.
   * @module model/ScheduleAutoImportRequest
   * @version 2.0
   */

  /**
   * Constructs a new <code>ScheduleAutoImportRequest</code>.
   * The message request to schedule the auto import
   * @alias module:model/ScheduleAutoImportRequest
   * @class
   * @param schedules {Array.<String>} Indicate the time span you want to import your catalog. (i.e. \"21:00:00\" to import your catalog at 9PM)
   */
  var exports = function(schedules) {
    var _this = this;

    _this['schedules'] = schedules;

  };

  /**
   * Constructs a <code>ScheduleAutoImportRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScheduleAutoImportRequest} obj Optional instance to populate.
   * @return {module:model/ScheduleAutoImportRequest} The populated <code>ScheduleAutoImportRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('schedules')) {
        obj['schedules'] = ApiClient.convertToType(data['schedules'], ['String']);
      }
      if (data.hasOwnProperty('localTimeZoneName')) {
        obj['localTimeZoneName'] = ApiClient.convertToType(data['localTimeZoneName'], 'String');
      }
    }
    return obj;
  }

  /**
   * Indicate the time span you want to import your catalog. (i.e. \"21:00:00\" to import your catalog at 9PM)
   * @member {Array.<String>} schedules
   */
  exports.prototype['schedules'] = undefined;
  /**
   * If null the local time zone name will be \"Romance Standard Time\"
   * @member {String} localTimeZoneName
   * @default 'Romance Standard Time'
   */
  exports.prototype['localTimeZoneName'] = 'Romance Standard Time';



  return exports;
}));


