/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrderMerchantECommerceSoftwareName', 'model/OrderMerchantECommerceSoftwareVersion', 'model/OrderMerchantOrderId'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OrderMerchantECommerceSoftwareName'), require('./OrderMerchantECommerceSoftwareVersion'), require('./OrderMerchantOrderId'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.SetMerchantOrderInfoRequest = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.OrderMerchantECommerceSoftwareName, root.BeezUpApi.OrderMerchantECommerceSoftwareVersion, root.BeezUpApi.OrderMerchantOrderId);
  }
}(this, function(ApiClient, OrderMerchantECommerceSoftwareName, OrderMerchantECommerceSoftwareVersion, OrderMerchantOrderId) {
  'use strict';




  /**
   * The SetMerchantOrderInfoRequest model module.
   * @module model/SetMerchantOrderInfoRequest
   * @version 2.0
   */

  /**
   * Constructs a new <code>SetMerchantOrderInfoRequest</code>.
   * @alias module:model/SetMerchantOrderInfoRequest
   * @class
   * @param orderMerchantOrderId {module:model/OrderMerchantOrderId} 
   */
  var exports = function(orderMerchantOrderId) {
    var _this = this;

    _this['order_MerchantOrderId'] = orderMerchantOrderId;


  };

  /**
   * Constructs a <code>SetMerchantOrderInfoRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SetMerchantOrderInfoRequest} obj Optional instance to populate.
   * @return {module:model/SetMerchantOrderInfoRequest} The populated <code>SetMerchantOrderInfoRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('order_MerchantOrderId')) {
        obj['order_MerchantOrderId'] = OrderMerchantOrderId.constructFromObject(data['order_MerchantOrderId']);
      }
      if (data.hasOwnProperty('order_MerchantECommerceSoftwareName')) {
        obj['order_MerchantECommerceSoftwareName'] = OrderMerchantECommerceSoftwareName.constructFromObject(data['order_MerchantECommerceSoftwareName']);
      }
      if (data.hasOwnProperty('order_MerchantECommerceSoftwareVersion')) {
        obj['order_MerchantECommerceSoftwareVersion'] = OrderMerchantECommerceSoftwareVersion.constructFromObject(data['order_MerchantECommerceSoftwareVersion']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/OrderMerchantOrderId} order_MerchantOrderId
   */
  exports.prototype['order_MerchantOrderId'] = undefined;
  /**
   * @member {module:model/OrderMerchantECommerceSoftwareName} order_MerchantECommerceSoftwareName
   */
  exports.prototype['order_MerchantECommerceSoftwareName'] = undefined;
  /**
   * @member {module:model/OrderMerchantECommerceSoftwareVersion} order_MerchantECommerceSoftwareVersion
   */
  exports.prototype['order_MerchantECommerceSoftwareVersion'] = undefined;



  return exports;
}));


