/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountId', 'model/BeezUPCommonMarketplaceTechnicalCode', 'model/BeezUPOrderId', 'model/OrderIdentifier', 'model/OrderMerchantOrderId'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccountId'), require('./BeezUPCommonMarketplaceTechnicalCode'), require('./BeezUPOrderId'), require('./OrderIdentifier'), require('./OrderMerchantOrderId'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.SetMerchantOrderInfoListRequestItem = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.AccountId, root.BeezUpApi.BeezUPCommonMarketplaceTechnicalCode, root.BeezUpApi.BeezUPOrderId, root.BeezUpApi.OrderIdentifier, root.BeezUpApi.OrderMerchantOrderId);
  }
}(this, function(ApiClient, AccountId, BeezUPCommonMarketplaceTechnicalCode, BeezUPOrderId, OrderIdentifier, OrderMerchantOrderId) {
  'use strict';




  /**
   * The SetMerchantOrderInfoListRequestItem model module.
   * @module model/SetMerchantOrderInfoListRequestItem
   * @version 2.0
   */

  /**
   * Constructs a new <code>SetMerchantOrderInfoListRequestItem</code>.
   * @alias module:model/SetMerchantOrderInfoListRequestItem
   * @class
   * @implements module:model/OrderIdentifier
   * @param marketplaceTechnicalCode {module:model/BeezUPCommonMarketplaceTechnicalCode} 
   * @param accountId {module:model/AccountId} 
   * @param beezUPOrderId {module:model/BeezUPOrderId} 
   * @param orderMerchantOrderId {module:model/OrderMerchantOrderId} 
   */
  var exports = function(marketplaceTechnicalCode, accountId, beezUPOrderId, orderMerchantOrderId) {
    var _this = this;

    OrderIdentifier.call(_this, marketplaceTechnicalCode, accountId, beezUPOrderId);
    _this['order_MerchantOrderId'] = orderMerchantOrderId;
  };

  /**
   * Constructs a <code>SetMerchantOrderInfoListRequestItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SetMerchantOrderInfoListRequestItem} obj Optional instance to populate.
   * @return {module:model/SetMerchantOrderInfoListRequestItem} The populated <code>SetMerchantOrderInfoListRequestItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      OrderIdentifier.constructFromObject(data, obj);
      if (data.hasOwnProperty('order_MerchantOrderId')) {
        obj['order_MerchantOrderId'] = OrderMerchantOrderId.constructFromObject(data['order_MerchantOrderId']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/OrderMerchantOrderId} order_MerchantOrderId
   */
  exports.prototype['order_MerchantOrderId'] = undefined;

  // Implement OrderIdentifier interface:
  /**
   * @member {module:model/BeezUPCommonMarketplaceTechnicalCode} marketplaceTechnicalCode
   */
exports.prototype['marketplaceTechnicalCode'] = undefined;

  /**
   * @member {module:model/AccountId} accountId
   */
exports.prototype['accountId'] = undefined;

  /**
   * @member {module:model/BeezUPOrderId} beezUPOrderId
   */
exports.prototype['beezUPOrderId'] = undefined;



  return exports;
}));


