/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LinksCreateStoreLink', 'model/LinksGetStoresLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LinksCreateStoreLink'), require('./LinksGetStoresLink'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.StoresLinks = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.LinksCreateStoreLink, root.BeezUpApi.LinksGetStoresLink);
  }
}(this, function(ApiClient, LinksCreateStoreLink, LinksGetStoresLink) {
  'use strict';




  /**
   * The StoresLinks model module.
   * @module model/StoresLinks
   * @version 2.0
   */

  /**
   * Constructs a new <code>StoresLinks</code>.
   * The action links
   * @alias module:model/StoresLinks
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>StoresLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StoresLinks} obj Optional instance to populate.
   * @return {module:model/StoresLinks} The populated <code>StoresLinks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('getStores')) {
        obj['getStores'] = LinksGetStoresLink.constructFromObject(data['getStores']);
      }
      if (data.hasOwnProperty('createStore')) {
        obj['createStore'] = LinksCreateStoreLink.constructFromObject(data['createStore']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/LinksGetStoresLink} getStores
   */
  exports.prototype['getStores'] = undefined;
  /**
   * @member {module:model/LinksCreateStoreLink} createStore
   */
  exports.prototype['createStore'] = undefined;



  return exports;
}));


