/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.StoreCountryIsoCodeAlpha3 = factory(root.BeezUpApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The StoreCountryIsoCodeAlpha3 model module.
   * @module model/StoreCountryIsoCodeAlpha3
   * @version 2.0
   */

  /**
   * Constructs a new <code>StoreCountryIsoCodeAlpha3</code>.
   * The country iso code alpha 3 based on the list of values /user/lov/StoreCountry
   * @alias module:model/StoreCountryIsoCodeAlpha3
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>StoreCountryIsoCodeAlpha3</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StoreCountryIsoCodeAlpha3} obj Optional instance to populate.
   * @return {module:model/StoreCountryIsoCodeAlpha3} The populated <code>StoreCountryIsoCodeAlpha3</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

    }
    return obj;
  }




  return exports;
}));


