/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TrackedOrder'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TrackedOrder'));
  } else {
    // Browser globals (root is window)
    if (!root.BeezUpApi) {
      root.BeezUpApi = {};
    }
    root.BeezUpApi.TrackedOrders = factory(root.BeezUpApi.ApiClient, root.BeezUpApi.TrackedOrder);
  }
}(this, function(ApiClient, TrackedOrder) {
  'use strict';




  /**
   * The TrackedOrders model module.
   * @module model/TrackedOrders
   * @version 2.0
   */

  /**
   * Constructs a new <code>TrackedOrders</code>.
   * @alias module:model/TrackedOrders
   * @class
   * @param orders {Array.<module:model/TrackedOrder>} 
   */
  var exports = function(orders) {
    var _this = this;

    _this['orders'] = orders;
  };

  /**
   * Constructs a <code>TrackedOrders</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackedOrders} obj Optional instance to populate.
   * @return {module:model/TrackedOrders} The populated <code>TrackedOrders</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('orders')) {
        obj['orders'] = ApiClient.convertToType(data['orders'], [TrackedOrder]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/TrackedOrder>} orders
   */
  exports.prototype['orders'] = undefined;



  return exports;
}));


