/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BeezUpApi);
  }
}(this, function(expect, BeezUpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BeezUpApi.ChangeOrderReporting();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChangeOrderReporting', function() {
    it('should create an instance of ChangeOrderReporting', function() {
      // uncomment below and update the code to test ChangeOrderReporting
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be.a(BeezUpApi.ChangeOrderReporting);
    });

    it('should have the property executionUUID (base name: "executionUUID")', function() {
      // uncomment below and update the code to test the property executionUUID
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be();
    });

    it('should have the property changeOrderType (base name: "changeOrderType")', function() {
      // uncomment below and update the code to test the property changeOrderType
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be();
    });

    it('should have the property sourceType (base name: "sourceType")', function() {
      // uncomment below and update the code to test the property sourceType
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be();
    });

    it('should have the property sourceUserId (base name: "sourceUserId")', function() {
      // uncomment below and update the code to test the property sourceUserId
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be();
    });

    it('should have the property sourceUserName (base name: "sourceUserName")', function() {
      // uncomment below and update the code to test the property sourceUserName
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be();
    });

    it('should have the property creationUtcDate (base name: "creationUtcDate")', function() {
      // uncomment below and update the code to test the property creationUtcDate
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be();
    });

    it('should have the property processingStatus (base name: "processingStatus")', function() {
      // uncomment below and update the code to test the property processingStatus
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdateUtcDate (base name: "lastUpdateUtcDate")', function() {
      // uncomment below and update the code to test the property lastUpdateUtcDate
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "errorMessage")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be();
    });

    it('should have the property ipAddress (base name: "ipAddress")', function() {
      // uncomment below and update the code to test the property ipAddress
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be();
    });

    it('should have the property testMode (base name: "testMode")', function() {
      // uncomment below and update the code to test the property testMode
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be();
    });

    it('should have the property details (base name: "details")', function() {
      // uncomment below and update the code to test the property details
      //var instane = new BeezUpApi.ChangeOrderReporting();
      //expect(instance).to.be();
    });

  });

}));
