/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BeezUpApi);
  }
}(this, function(expect, BeezUpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BeezUpApi.InputFileFetchConfiguration();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InputFileFetchConfiguration', function() {
    it('should create an instance of InputFileFetchConfiguration', function() {
      // uncomment below and update the code to test InputFileFetchConfiguration
      //var instane = new BeezUpApi.InputFileFetchConfiguration();
      //expect(instance).to.be.a(BeezUpApi.InputFileFetchConfiguration);
    });

    it('should have the property uri (base name: "uri")', function() {
      // uncomment below and update the code to test the property uri
      //var instane = new BeezUpApi.InputFileFetchConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property credential (base name: "credential")', function() {
      // uncomment below and update the code to test the property credential
      //var instane = new BeezUpApi.InputFileFetchConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property downloadCatalogStrategy (base name: "downloadCatalogStrategy")', function() {
      // uncomment below and update the code to test the property downloadCatalogStrategy
      //var instane = new BeezUpApi.InputFileFetchConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property compressionFormatStrategy (base name: "compressionFormatStrategy")', function() {
      // uncomment below and update the code to test the property compressionFormatStrategy
      //var instane = new BeezUpApi.InputFileFetchConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property compressedRelativePath (base name: "compressedRelativePath")', function() {
      // uncomment below and update the code to test the property compressedRelativePath
      //var instane = new BeezUpApi.InputFileFetchConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property downloadTimeout (base name: "downloadTimeout")', function() {
      // uncomment below and update the code to test the property downloadTimeout
      //var instane = new BeezUpApi.InputFileFetchConfiguration();
      //expect(instance).to.be();
    });

  });

}));
