/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BeezUpApi);
  }
}(this, function(expect, BeezUpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BeezUpApi.MarketplaceChannelCatalog();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MarketplaceChannelCatalog', function() {
    it('should create an instance of MarketplaceChannelCatalog', function() {
      // uncomment below and update the code to test MarketplaceChannelCatalog
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be.a(BeezUpApi.MarketplaceChannelCatalog);
    });

    it('should have the property marketplaceTechnicalCode (base name: "marketplaceTechnicalCode")', function() {
      // uncomment below and update the code to test the property marketplaceTechnicalCode
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be();
    });

    it('should have the property marketplaceBusinessCode (base name: "marketplaceBusinessCode")', function() {
      // uncomment below and update the code to test the property marketplaceBusinessCode
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be();
    });

    it('should have the property marketplaceMarketPlaceId (base name: "marketplaceMarketPlaceId")', function() {
      // uncomment below and update the code to test the property marketplaceMarketPlaceId
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be();
    });

    it('should have the property marketplaceIsoCountryCodeAlpha2 (base name: "marketplaceIsoCountryCodeAlpha2")', function() {
      // uncomment below and update the code to test the property marketplaceIsoCountryCodeAlpha2
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be();
    });

    it('should have the property beezUPChannelId (base name: "beezUPChannelId")', function() {
      // uncomment below and update the code to test the property beezUPChannelId
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be();
    });

    it('should have the property beezUPChannelCatalogId (base name: "beezUPChannelCatalogId")', function() {
      // uncomment below and update the code to test the property beezUPChannelCatalogId
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be();
    });

    it('should have the property beezUPStoreId (base name: "beezUPStoreId")', function() {
      // uncomment below and update the code to test the property beezUPStoreId
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be();
    });

    it('should have the property beezUPStoreName (base name: "beezUPStoreName")', function() {
      // uncomment below and update the code to test the property beezUPStoreName
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be();
    });

    it('should have the property marketplaceMerchantIdentifiers (base name: "marketplaceMerchantIdentifiers")', function() {
      // uncomment below and update the code to test the property marketplaceMerchantIdentifiers
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be();
    });

    it('should have the property marketplaceAccountId (base name: "marketplaceAccountId")', function() {
      // uncomment below and update the code to test the property marketplaceAccountId
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be();
    });

    it('should have the property lovLinks (base name: "lovLinks")', function() {
      // uncomment below and update the code to test the property lovLinks
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be();
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instane = new BeezUpApi.MarketplaceChannelCatalog();
      //expect(instance).to.be();
    });

  });

}));
