/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BeezUpApi);
  }
}(this, function(expect, BeezUpApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BeezUpApi.PublicationFeedReporting();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PublicationFeedReporting', function() {
    it('should create an instance of PublicationFeedReporting', function() {
      // uncomment below and update the code to test PublicationFeedReporting
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be.a(BeezUpApi.PublicationFeedReporting);
    });

    it('should have the property feedType (base name: "feedType")', function() {
      // uncomment below and update the code to test the property feedType
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

    it('should have the property startUtcDate (base name: "startUtcDate")', function() {
      // uncomment below and update the code to test the property startUtcDate
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

    it('should have the property endUtcDate (base name: "endUtcDate")', function() {
      // uncomment below and update the code to test the property endUtcDate
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

    it('should have the property processingStatus (base name: "processingStatus")', function() {
      // uncomment below and update the code to test the property processingStatus
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

    it('should have the property exportedProducts (base name: "exportedProducts")', function() {
      // uncomment below and update the code to test the property exportedProducts
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

    it('should have the property transmittedItems (base name: "transmittedItems")', function() {
      // uncomment below and update the code to test the property transmittedItems
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

    it('should have the property publishedItems (base name: "publishedItems")', function() {
      // uncomment below and update the code to test the property publishedItems
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

    it('should have the property publishedItemsWithWarning (base name: "publishedItemsWithWarning")', function() {
      // uncomment below and update the code to test the property publishedItemsWithWarning
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

    it('should have the property failedItems (base name: "failedItems")', function() {
      // uncomment below and update the code to test the property failedItems
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "errorMessage")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

    it('should have the property htmlReportUrl (base name: "htmlReportUrl")', function() {
      // uncomment below and update the code to test the property htmlReportUrl
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

    it('should have the property htmlReportGenerationErrorMessage (base name: "htmlReportGenerationErrorMessage")', function() {
      // uncomment below and update the code to test the property htmlReportGenerationErrorMessage
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

    it('should have the property completed (base name: "completed")', function() {
      // uncomment below and update the code to test the property completed
      //var instane = new BeezUpApi.PublicationFeedReporting();
      //expect(instance).to.be();
    });

  });

}));
